import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {inventory,checkOrigins,containsPrivateKey} from '../web_asset_package.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'fayda-web-assets-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
test('inventories exact bytes and contained relative dependency links',t=>{const root=fixture(t);fs.mkdirSync(path.join(root,'deps'));fs.writeFileSync(path.join(root,'deps/a.js'),'module.exports=1');fs.symlinkSync('deps/a.js',path.join(root,'a.js'));const rows=inventory(root);assert.equal(rows.length,2);assert.equal(rows[0].target,'deps/a.js');assert.match(rows[1].sha256,/^[a-f0-9]{64}$/);fs.appendFileSync(path.join(root,'deps/a.js'),'2');assert.notEqual(inventory(root)[1].sha256,rows[1].sha256);});
test('rejects escaping or dangling runtime symlinks',t=>{const root=fixture(t);fs.symlinkSync('../outside',path.join(root,'escape'));assert.throws(()=>inventory(root));fs.unlinkSync(path.join(root,'escape'));fs.symlinkSync('missing',path.join(root,'missing-link'));assert.throws(()=>inventory(root));});
test('refuses environment and private-key material',t=>{const root=fixture(t);fs.writeFileSync(path.join(root,'.env.production'),'KEY=synthetic');assert.throws(()=>inventory(root),/credential path/);fs.unlinkSync(path.join(root,'.env.production'));fs.writeFileSync(path.join(root,'document.txt'),'-----BEGIN PRIVATE KEY-----\n'+'A'.repeat(64)+'\n-----END PRIVATE KEY-----');assert.throws(()=>inventory(root),/Private-key/);});
test('requires intended origins in both served asset sets',t=>{const root=fixture(t),a=path.join(root,'admin'),p=path.join(root,'public');fs.mkdirSync(a);fs.mkdirSync(p);fs.writeFileSync(path.join(a,'a.js'),'fetch("https://api.faydamed.tech/api")');fs.writeFileSync(path.join(p,'a.js'),'fetch("https://api.faydamed.tech/api")');assert.equal(checkOrigins(a,p).admin.scanned_files,1);fs.writeFileSync(path.join(p,'a.js'),'fetch("https://unrelated.example/api")');assert.throws(()=>checkOrigins(a,p),/absent/);});
test('rejects localhost fallbacks even when real origin is also present',t=>{const root=fixture(t),a=path.join(root,'admin'),p=path.join(root,'public');fs.mkdirSync(a);fs.mkdirSync(p);fs.writeFileSync(path.join(a,'a.js'),'https://api.faydamed.tech/api');fs.writeFileSync(path.join(p,'a.js'),'https://api.faydamed.tech http://localhost:8000/api');assert.throws(()=>checkOrigins(a,p),/Local application origin/);});

test('bare crypto parser delimiters are not private-key payloads',()=>{assert.equal(containsPrivateKey(Buffer.from('parse("-----BEGIN PRIVATE KEY-----")')),false);assert.equal(containsPrivateKey(Buffer.from('-----BEGIN PRIVATE KEY-----\\n'+'B'.repeat(64))),true);});
