"use client"
import Link from 'next/link'
import {useState} from 'react'
import {useParams} from 'next/navigation'
import {useAuth} from '@/hooks/useAuth'
import {useGetRecallFollowUpQuery,usePharmacyStockActionMutation,RecallFollowUp} from '@/store/api/pharmacyApiSlice'
import {Field,errorMessage} from '@/components/pharmacy/fields'
import {Button} from '@/components/ui/button'
export default function FollowUp(){
 const params=useParams();const noticeId=Number(params.id);const fillId=Number(params.fillId);const {user}=useAuth();const role=user?.role||'';const allowed=['pharmacist','pharmacy_technician'].includes(role);const [page,setPage]=useState(1)
 const {currentData,isFetching,isError,refetch}=useGetRecallFollowUpQuery({noticeId,fillId,page},{skip:!allowed||!Number.isInteger(noticeId)||!Number.isInteger(fillId)||noticeId<1||fillId<1});const d=currentData?.data
 if(!allowed)return <p>Pharmacy staff access is required.</p>
 return <div className="space-y-5 min-w-0"><Link className="underline" href={`/dashboard/pharmacy/recalls/${noticeId}`}>Back to notice and affected fills</Link><h1 className="text-3xl font-bold text-primary">Recall follow-up</h1><p>Synthetic preview. Record actions already taken outside this system and the supporting evidence. Saving an entry does not send a message, change a prescription, move stock or clear a recall hold.</p>{isError?<p role="alert">Follow-up could not be loaded. <Button variant="outline" onClick={()=>refetch()}>Retry</Button></p>:isFetching&&!d?<p role="status">Loading follow-up…</p>:d&&<>
 <section className="border rounded p-4 space-y-2 break-words"><h2 className="text-xl font-semibold">{d.reference}</h2><Link className="block underline" href={`/dashboard/pharmacy/${d.fill.prescription_id}#fill-${d.fill.id}`}>{d.fill.rx_number} · Fill {d.fill.fill_number}</Link><p>Fill status: {d.fill.fulfillment_status} · Follow-up: {d.status.replaceAll('_',' ')}</p><Link className="block underline" href={`/dashboard/pharmacy/stock/${d.fill.stock_lot_id}`}>Stock receipt #{d.fill.stock_lot_id}</Link></section>
 <Entry key={`${user?.id}-${noticeId}-${fillId}`} data={d} role={role} refreshing={isFetching} saved={()=>setPage(1)}/>
 <section className="space-y-3"><h2 className="text-xl font-semibold">Retained follow-up history</h2><p>New entries preserve earlier statements. A pharmacist can reopen completed follow-up when new information needs attention. Completion concerns this fill only and does not close the organization recall.</p>{d.events.data.map(e=><div key={e.id} className="border rounded p-4 space-y-2 break-words"><h3 className="font-semibold">{e.action.replaceAll('_',' ')} · Entry {e.version}</h3><p>Occurred {e.occurred_on}{e.method?` · ${e.method.replaceAll('_',' ')}`:''}</p><p>Recorded by staff #{e.actor_id} · {e.created_at}</p><p className="whitespace-pre-wrap">{e.note}</p><p className="whitespace-pre-wrap">Evidence: {e.evidence}</p></div>)}{!d.events.data.length&&<p>No follow-up entries recorded.</p>}<div className="flex flex-wrap gap-3 items-center"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous entries</Button><span>Page {page} of {d.events.last_page} · {d.events.total} entries</span><Button variant="outline" disabled={page>=d.events.last_page} onClick={()=>setPage(page+1)}>Next entries</Button></div></section></>}</div>
}
function Entry({data:d,role,refreshing,saved}:{data:RecallFollowUp;role:string;refreshing:boolean;saved:()=>void}){
 const pharmacist=role==='pharmacist';const closed=d.status==='completed';const canComplete=['cancelled','collected','delivered'].includes(d.fill.fulfillment_status);const options=closed?['reopen']:[...(pharmacist?['assessment']:[]),'contact_attempt','response','follow_up',...(pharmacist&&canComplete?['complete']:[])];const [action,setAction]=useState(options[0]);const [key,setKey]=useState(()=>crypto.randomUUID());const [error,setError]=useState('');const [mutate,{isLoading}]=usePharmacyStockActionMutation()
 if(closed&&!pharmacist)return <p>A pharmacist must reopen completed follow-up before staff can add entries.</p>
 const chosen=options.includes(action)?action:options[0]
 return <section className="border rounded p-4 space-y-3"><h2 className="text-xl font-semibold">{closed?'Reopen follow-up':'Record follow-up evidence'}</h2>{!canComplete&&!closed&&<p>Resolve the outstanding fill reservation before completing follow-up. Use the linked prescription to review and cancel an unfulfilled fill.</p>}<form key={key} className="grid gap-3 max-w-2xl" onSubmit={async e=>{e.preventDefault();setError('');const body=Object.fromEntries(new FormData(e.currentTarget));try{await mutate({path:`recall-notices/${d.notice_id}/fills/${d.fill.id}/follow-up/events`,body:{...body,request_id:key,version:d.version,action:chosen}}).unwrap();setKey(crypto.randomUUID());saved()}catch(e){setError(errorMessage(e))}}}>
 <label className="grid gap-1 text-sm">Entry type<select className="border rounded p-2 bg-background" value={chosen} onChange={e=>setAction(e.target.value)}>{options.map(a=><option key={a} value={a}>{a.replaceAll('_',' ')}</option>)}</select></label><Field name="occurred_on" label="Date action occurred" type="date"/>
 {['contact_attempt','response'].includes(chosen)&&<label className="grid gap-1 text-sm">Contact method<select name="method" className="border rounded p-2 bg-background" required defaultValue=""><option value="">Select method</option>{['phone','secure_message','in_person','other'].map(m=><option key={m} value={m}>{m.replaceAll('_',' ')}</option>)}</select></label>}
 <label className="grid gap-1 text-sm">{chosen==='complete'?'Pharmacist assessment and reason this fill follow-up is complete':'Action, outcome and next steps'}<textarea name="note" className="border rounded p-2 bg-background" required maxLength={5000}/></label><Field name="evidence" label="Supporting record / evidence reference" maxLength={2000}/>{chosen==='complete'&&<label className="flex items-start gap-2 text-sm"><input type="checkbox" required/>I reviewed the outcome and supporting evidence. This does not release stock or close the recall notice.</label>}{error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}<Button disabled={isLoading||refreshing}>{isLoading?'Saving…':'Save follow-up entry'}</Button></form></section>
}
