"use client"
import Link from 'next/link'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {useAuth} from '@/hooks/useAuth'
import {useGetRecallNoticesQuery,usePharmacyStockActionMutation} from '@/store/api/pharmacyApiSlice'
import {Field,errorMessage} from '@/components/pharmacy/fields'
import {Button} from '@/components/ui/button'
export default function Recalls(){
 const {user}=useAuth();const allowed=['pharmacist','pharmacy_technician'].includes(user?.role||'');const router=useRouter()
 const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [allLots,setAllLots]=useState(false);const [requestId]=useState(()=>crypto.randomUUID());const [error,setError]=useState('')
 const {currentData,isFetching,isError,refetch}=useGetRecallNoticesQuery({page,search},{skip:!allowed});const [mutate,{isLoading}]=usePharmacyStockActionMutation()
 if(!allowed)return <p>Pharmacy staff access is required.</p>
 return <div className="space-y-5 min-w-0"><Link className="underline" href="/dashboard/pharmacy/stock">Back to inventory</Link><h1 className="text-3xl font-bold text-primary">Organization recall register</h1><p>Synthetic preview. A pharmacist records verified product and lot scope. Matching medication stock is held across all organization locations, including later receipts. Affected stock and fills are visible only at your assigned locations.</p><p className="text-sm">This register does not receive an automated recall feed or contact patients. Notices are retained; release, return, disposal and recall closure require a separate approved workflow.</p>
 {user?.role==='pharmacist'&&<details><summary className="underline cursor-pointer">Record a recall notice</summary><form className="grid gap-3 mt-3 max-w-2xl" onSubmit={async e=>{e.preventDefault();setError('');const d=Object.fromEntries(new FormData(e.currentTarget));try{const result=await mutate({path:'recall-notices',body:{request_id:requestId,product_description:d.product_description,reference:d.reference,evidence:d.evidence,all_lots:allLots,lot_number:allLots?null:d.lot_number,ndcs:String(d.ndcs).split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}}).unwrap();router.push(`/dashboard/pharmacy/recalls/${result.data.id}`)}catch(e){setError(errorMessage(e))}}}>
 <Field name="product_description" label="Product name, strength and form from notice" maxLength={255}/><Field name="reference" label="Recall notice reference / source" maxLength={2000}/><label className="grid gap-1 text-sm">Verified NDC representations — one per line<textarea name="ndcs" required maxLength={300} className="border rounded p-2 bg-background"/></label><p className="text-sm">Include each verified 10- or 11-digit representation needed to match your inventory. Leading zeros are preserved and hyphens ignored. No conversion between 10 and 11 digits is inferred. Ingredient stock has its own receipt-level recall workflow.</p>
 <label className="flex gap-2 items-start"><input type="checkbox" checked={allLots} onChange={e=>setAllLots(e.target.checked)}/>The source explicitly recalls all lots of these product codes.</label>{!allLots&&<Field name="lot_number" label="Exact manufacturer lot number" maxLength={100}/>}<p className="text-sm">Lot matching ignores letter case and surrounding spaces. Ranges and partial matches are not supported; record each specific lot separately unless the notice covers all lots.</p>
 <label className="grid gap-1 text-sm">Evidence of product-code and lot verification<textarea name="evidence" required maxLength={5000} className="border rounded p-2 bg-background"/></label><label className="flex gap-2 items-start"><input type="checkbox" required/>I verified this scope against the source and understand that it places an organization-wide hold on matching medication stock.</label>{error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}<Button disabled={isLoading}>{isLoading?'Recording…':'Record notice and hold matching stock'}</Button></form></details>}
 <label className="grid gap-1 text-sm">Search notice reference, product or lot<input className="border rounded p-2 bg-background" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label>
 {isError?<p role="alert">Notices could not be loaded. <Button variant="outline" onClick={()=>refetch()}>Retry</Button></p>:isFetching?<p role="status">Loading notices…</p>:<div className="space-y-3">{currentData?.data.data.map(n=><div key={n.id} className="border rounded p-4 space-y-2 break-words"><Link className="underline font-semibold" href={`/dashboard/pharmacy/recalls/${n.id}`}>{n.reference}</Link><p>{n.product_description} · {n.all_lots?'All lots':`Lot ${n.lot_number}`}</p><p>NDC: {n.ndcs.join(', ')}</p><p className="text-sm">Recorded {n.created_at} · Staff #{n.created_by}</p></div>)}{!currentData?.data.data.length&&<p>No notices match this view.</p>}</div>}
 <div className="flex flex-wrap gap-3 items-center"><Button variant="outline" disabled={isFetching||page===1} onClick={()=>setPage(page-1)}>Previous notices</Button><span>Page {page} of {currentData?.data.last_page||1}</span><Button variant="outline" disabled={isFetching||page>=(currentData?.data.last_page||1)} onClick={()=>setPage(page+1)}>Next notices</Button></div></div>
}
