"use client"
import Link from 'next/link'
import {FormEvent,useRef,useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card'
import {Field,Choice,errorMessage} from '@/components/pharmacy/fields'
import {useGetIngredientLotsQuery,useGetIngredientLotQuery,useGetPharmacyLocationsQuery,usePharmacyStockActionMutation} from '@/store/api/pharmacyApiSlice'
function Receipt({onDone}:{onDone:(id:number)=>void}){
 const {data:locations,isError}=useGetPharmacyLocationsQuery();const [save,{isLoading}]=usePharmacyStockActionMutation();const [error,setError]=useState('');const request=useRef('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const d=Object.fromEntries(new FormData(e.currentTarget));if(!request.current)request.current=crypto.randomUUID();try{const r=await save({path:'ingredient-lots',body:{...d,location_id:Number(d.location_id),request_id:request.current}}).unwrap();onDone(r.data.id)}catch(e){setError(errorMessage(e))}}
 return <form onSubmit={submit} className="space-y-4"><p>New receipts are quarantined until a pharmacist records their receiving review. Each receipt retains its own stock balance and history.</p><label className="grid gap-1 text-sm">Receiving location<select required name="location_id" className="border rounded p-2 bg-background"><option value="">Select location</option>{locations?.data.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{isError&&<p role="alert">Could not load locations.</p>}<div className="grid md:grid-cols-2 gap-3"><Field name="ingredient_name" label="Ingredient name (match formulation exactly)"/><Field name="supplier" label="Supplier"/><Field name="lot_number" label="Supplier lot number"/><Field name="quantity" label="Received quantity" type="number" min="0.001" max="999999.999" step="0.001"/><Choice name="quantity_unit" label="Quantity unit" options={['mg','g','mL','each','capsule','tablet']}/><Field name="expires_on" label="Ingredient expiration date" type="date"/><Field name="specification" label="Specification / grade (match formulation exactly)"/><Field name="certificate_reference" label="Certificate evidence reference"/><Field name="receipt_reference" label="Unique receiving document / line reference"/></div>{error&&<p role="alert">{error}</p>}<Button disabled={isLoading||!locations?.data.length}>Record quarantined receipt</Button></form>
}
function Detail({id}:{id:number}){
 const {user}=useAuth();const {data,isFetching,isError}=useGetIngredientLotQuery(id);const [save,{isLoading}]=usePharmacyStockActionMutation();const [error,setError]=useState('');if(isFetching)return <p>Loading ingredient lot…</p>;if(isError||!data)return <p role="alert">Could not load ingredient lot.</p>;const lot=data.data
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const d=Object.fromEntries(new FormData(e.currentTarget));try{await save({path:`ingredient-lots/${id}/status`,body:{...d,version:lot.version,status:lot.status==='available'?'quarantined':'available'}}).unwrap()}catch(e){setError(errorMessage(e))}}
 return <div className="space-y-4"><h2 className="text-xl font-semibold">{lot.ingredient_name} · Lot {lot.lot_number}</h2><p>{lot.status} · {lot.on_hand} {lot.quantity_unit} on hand · {lot.reserved} reserved</p><p>Supplier: {lot.supplier} · Expires: {lot.expires_on}</p><p>Specification: {lot.specification}</p><p>Certificate: {lot.certificate_reference}</p><p>Receiving reference: {lot.receipt_reference}</p>{user?.role==='pharmacist'&&<form onSubmit={submit} className="border rounded p-4 space-y-3"><h3 className="font-semibold">{lot.status==='available'?'Place lot in quarantine':'Pharmacist receiving review'}</h3><p className="text-sm">Record the identity, specification, certificate and physical receiving review. A reference alone does not verify source quality. Quarantine retains existing reservations; release those separately from their worksheets.</p><Field name="evidence" label="Review findings and evidence reference"/>{error&&<p role="alert">{error}</p>}<Button disabled={isLoading}>{lot.status==='available'?'Quarantine lot':'Mark available for reservation'}</Button></form>}<h3 className="font-semibold">Custody history</h3>{lot.events.map(e=><div key={e.id} className="border-b py-2 text-sm"><strong>{e.action.replaceAll('_',' ')}</strong> · {e.quantity} {lot.quantity_unit} · User {e.actor_id} · {e.created_at}<p>{String((JSON.parse(e.details) as {evidence?:string;receipt_reference?:string}).evidence||(JSON.parse(e.details) as {receipt_reference?:string}).receipt_reference||'')}</p>{e.batch_id&&<p>Worksheet reference: {e.batch_id}</p>}</div>)}</div>
}
export default function Ingredients(){
 const {user}=useAuth();const allowed=['pharmacist','pharmacy_technician'].includes(user?.role||'');const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [selected,setSelected]=useState<number|null>(null);const [adding,setAdding]=useState(false)
 const {currentData,isFetching,isError,refetch}=useGetIngredientLotsQuery({page,search},{skip:!allowed});const {data:locations}=useGetPharmacyLocationsQuery(undefined,{skip:!allowed})
 if(!allowed)return <p>Ingredient inventory requires pharmacy staff access.</p>
 return <div className="space-y-6"><Link className="underline" href="/dashboard/pharmacy/compounding">← Compounding records</Link><h1 className="text-3xl font-bold text-primary">Ingredient inventory</h1><p className="border rounded bg-muted/30 p-4 text-sm">Synthetic preview. Receipts, quarantine and batch reservations are tracked. Manufacturing consumption, adjustments, transfers, recalls and finished-product release are not yet available.</p>{selected!==null||adding?<Card><CardHeader><Button variant="outline" onClick={()=>{setSelected(null);setAdding(false)}}>Back to ingredient inventory</Button></CardHeader><CardContent>{selected!==null?<Detail key={selected} id={selected}/>:<Receipt onDone={id=>{setSelected(id);setAdding(false)}}/>}</CardContent></Card>:<Card><CardHeader><CardTitle>Ingredient receipts</CardTitle><Button onClick={()=>setAdding(true)}>Receive ingredient stock</Button></CardHeader><CardContent className="space-y-4"><Input aria-label="Search ingredients or lots" placeholder="Search ingredient name or lot" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/>{isError?<p role="alert">Could not load stock. <Button onClick={()=>refetch()}>Retry</Button></p>:isFetching?<p>Loading stock…</p>:<>{currentData?.data.data.map(l=><div key={l.id} className="flex justify-between gap-3 border-b py-3"><div>{l.ingredient_name} · {l.lot_number}<p className="text-sm">{locations?.data.find(x=>x.id===l.location_id)?.name} · {l.status} · Expires {l.expires_on}</p><p className="text-sm">{l.on_hand} {l.quantity_unit} on hand · {l.reserved} reserved</p></div><Button variant="outline" onClick={()=>setSelected(l.id)}>Open lot {l.lot_number}</Button></div>)}{!currentData?.data.total&&<p>No ingredient receipts found.</p>}</>}<div className="flex gap-3 items-center"><Button variant="outline" disabled={page===1||isFetching} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page} / {currentData?.data.last_page||1}</span><Button variant="outline" disabled={isFetching||page>=(currentData?.data.last_page||1)} onClick={()=>setPage(page+1)}>Next</Button></div></CardContent></Card>}</div>
}
