"use client"
import Link from 'next/link'
import {useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {useGetPharmacyLocationsQuery,useGetPharmacyStockQuery,usePharmacyStockActionMutation,PharmacyLot} from '@/store/api/pharmacyApiSlice'
import {Field,Choice,errorMessage} from '@/components/pharmacy/fields'
import {Button} from '@/components/ui/button'
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card'
export default function PharmacyStock(){
 const {user}=useAuth();const role=user?.role||'';const [location,setLocation]=useState('');const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [key,setKey]=useState(()=>crypto.randomUUID());const [error,setError]=useState('');const [success,setSuccess]=useState('')
 const {data:locations}=useGetPharmacyLocationsQuery();const {currentData,isFetching,isError}=useGetPharmacyStockQuery({location_id:location?Number(location):undefined,search,page});const [mutate,{isLoading}]=usePharmacyStockActionMutation()
 async function save(path:string,body:Record<string,unknown>,method?:string){setError('');setSuccess('');try{await mutate({path,body,method}).unwrap();setSuccess('Saved.');if(path==='stock')setKey(crypto.randomUUID())}catch(e){setError(errorMessage(e))}}
 return <div className="space-y-6"><Link className="underline" href="/dashboard/pharmacy">Back to pharmacy</Link><h1 className="text-3xl font-bold text-primary">Locations and inventory</h1><p>Development preview · Synthetic stock only. Every receipt belongs to one pharmacy location. Stock reservations are checked again before handover.</p>{error&&<p className="text-destructive" role="alert">{error}</p>}{success&&<p role="status">{success}</p>}
 <Card><CardHeader><CardTitle>Pharmacy locations</CardTitle></CardHeader><CardContent className="space-y-4">{locations?.data.map(l=><div key={l.id}><strong>{l.name}</strong> · {l.address}<p className="text-sm text-muted-foreground">License reference: {l.license_reference} · {l.active?'Active':'Inactive'}</p></div>)}{!locations?.data.length&&<p>A platform administrator must record a pharmacy location before intake or stock receipt.</p>}
 {role==='admin'&&<details><summary className="underline cursor-pointer">Add pharmacy location</summary><form className="grid gap-3 mt-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save('locations',Object.fromEntries(new FormData(e.currentTarget)))}}><Field name="name" label="Location name"/><Field name="address" label="Pharmacy address"/><Field name="license_reference" label="Pharmacy license reference"/><p className="text-xs">A reference does not verify licensure. Credential verification and staff location assignments are still required before operational use.</p><Button disabled={isLoading}>Add location</Button></form></details>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Stock receipts and lots</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm">Pharmacy location<select className="border rounded p-2 bg-background" value={location} onChange={e=>{setLocation(e.target.value);setPage(1)}}><option value="">All locations in my organization</option>{locations?.data.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="grid gap-1 text-sm">Search NDC or medication<input className="border rounded p-2 bg-background" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label></div>
 {isError?<p role="alert">Stock could not be loaded.</p>:isFetching?<p role="status">Loading stock…</p>:<div className="space-y-3">{currentData?.data.data.map(l=><Lot key={`${l.id}-${l.version}`} lot={l} location={locations?.data.find(x=>x.id===l.location_id)?.name||String(l.location_id)} pharmacist={role==='pharmacist'} disabled={isLoading} save={body=>save(`stock/${l.id}/status`,body,'PUT')}/>)}{!currentData?.data.data.length&&<p>No stock receipts found.</p>}</div>}
 <div className="flex gap-3 items-center"><Button variant="outline" disabled={page===1||isFetching} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page} of {currentData?.data.last_page||1}</span><Button variant="outline" disabled={page>=(currentData?.data.last_page||1)||isFetching} onClick={()=>setPage(page+1)}>Next</Button></div>
 {['pharmacist','pharmacy_technician'].includes(role)&&<details><summary className="underline cursor-pointer">Receive stock</summary><form key={key} className="grid gap-3 mt-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));save('stock',{...body,location_id:Number(body.location_id),request_id:key})}}><label className="grid gap-1 text-sm">Receiving location<select className="border rounded p-2 bg-background" name="location_id" required defaultValue={location}><option value="">Select location</option>{locations?.data.filter(l=>l.active).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><Field name="receipt_reference" label="Supplier receipt reference"/><Field name="medication" label="Product name / strength / form as supplied"/><Field name="ndc" label="NDC as printed (preserve leading zeros)"/><Field name="lot_number" label="Manufacturer lot number"/><Field name="expires_on" label="Verified expiration date" type="date"/><Field name="quantity" label="Quantity received in dispensing units" type="number" min="0.001" step="0.001"/><Choice name="quantity_unit" label="Dispensing quantity unit" options={['tablet','capsule','mL','g','each']}/><p className="text-sm md:col-span-2">Use the same unit as the prescription. Package-size conversions and drug catalogue validation are not yet automated. Compounding ingredients and batch records need their dedicated workflow.</p><Button disabled={isLoading}>Record stock receipt</Button></form></details>}</CardContent></Card></div>
}
function Lot({lot:l,location,pharmacist,disabled,save}:{lot:PharmacyLot;location:string;pharmacist:boolean;disabled:boolean;save:(d:Record<string,unknown>)=>void}){return <div className="border rounded p-4 space-y-2"><h3 className="font-semibold">{l.medication} · NDC {l.ndc}</h3><p className="text-sm">{location} · Receipt #{l.id} · Lot {l.lot_number} · Expires {l.expires_on} · {l.status}</p><p>On hand {l.on_hand} · Reserved {l.reserved} · Available {(Number(l.on_hand)-Number(l.reserved)).toFixed(3)} {l.quantity_unit}</p><p className="text-xs text-muted-foreground">Receipt evidence: {l.receipt_reference}</p>{pharmacist&&<details><summary className="text-sm underline cursor-pointer">Quarantine or release stock</summary><form className="grid gap-3 md:grid-cols-2 mt-3" onSubmit={e=>{e.preventDefault();save({...Object.fromEntries(new FormData(e.currentTarget)),version:l.version})}}><Choice name="status" label="Stock status" options={['quarantined','available']} defaultValue={l.status==='available'?'quarantined':'available'}/><Field name="note" label="Reason / evidence"/><Button disabled={disabled}>Save stock status</Button></form></details>}</div>}
