"use client"
import Link from 'next/link'
import {useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {useGetPharmacyLocationsQuery,useGetPharmacyStaffQuery,usePharmacyStockActionMutation} from '@/store/api/pharmacyApiSlice'
import {Field,Choice,errorMessage} from '@/components/pharmacy/fields'
import {Button} from '@/components/ui/button'
export default function PharmacyStaff(){
 const {user}=useAuth();const allowed=user?.role==='admin';const {data:locations}=useGetPharmacyLocationsQuery(undefined,{skip:!allowed});const {currentData,isError}=useGetPharmacyStaffQuery(undefined,{skip:!allowed});const [save,{isLoading}]=usePharmacyStockActionMutation();const [location,setLocation]=useState('');const [staff,setStaff]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const d=currentData?.data;const assignment=d?.assignments.find(a=>a.location_id===Number(location)&&a.user_id===Number(staff))
 if(!allowed)return <p>Only an organization’s platform administrator can manage pharmacy assignments.</p>
 return <div className="max-w-4xl space-y-5"><Link href="/dashboard/pharmacy" className="underline">Back to pharmacy</Link><h1 className="text-3xl font-bold text-primary">Pharmacy staff access</h1><p>Assign each staff member to the locations they serve. Expired or revoked assignments block access immediately. An assignment does not verify professional licensure.</p>{isError&&<p role="alert">Could not load assignments. Refresh before making changes.</p>}
 <form key={`${location}-${staff}-${assignment?.version||0}`} className="grid gap-4 md:grid-cols-2" onSubmit={async e=>{e.preventDefault();setError('');setMessage('');const f=Object.fromEntries(new FormData(e.currentTarget));try{await save({path:'staff',method:'PUT',body:{...f,location_id:Number(location),user_id:Number(staff),active:f.active==='active',version:assignment?.version||0}}).unwrap();setMessage('Assignment saved.')}catch(e){setError(errorMessage(e))}}}>
 <label>Pharmacy location<select className="border rounded p-2 w-full bg-background" required value={location} onChange={e=>setLocation(e.target.value)}><option value="">Select location</option>{locations?.data.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Staff member<select className="border rounded p-2 w-full bg-background" required value={staff} onChange={e=>setStaff(e.target.value)}><option value="">Select staff</option>{d?.staff.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} · {s.role.replaceAll('_',' ')}</option>)}</select></label>
 <Choice name="active" label="Access" options={['active','revoked']} defaultValue={assignment&&!assignment.active?'revoked':'active'}/><Field name="valid_until" label="Valid through" type="date" defaultValue={assignment?.valid_until}/><Field name="reason" label="Reason for assignment or revocation"/><Button disabled={isLoading||!d||isError}>Save assignment</Button></form>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <h2 className="text-xl font-semibold">Assignments</h2><ul className="space-y-3">{d?.assignments.map(a=><li key={a.id}>{locations?.data.find(l=>l.id===a.location_id)?.name} · Staff #{a.user_id} · {a.active?'Assigned':'Revoked'} · Valid through {a.valid_until} <Button variant="outline" onClick={()=>{setLocation(String(a.location_id));setStaff(String(a.user_id))}}>Edit assignment</Button></li>)}</ul><h2 className="text-xl font-semibold">Recent access changes</h2><ul>{d?.history.map(h=><li key={h.id}>{h.created_at} · Location #{h.location_id} · Staff #{h.user_id} · Changed by #{h.actor_id}<details><summary>Recorded evidence</summary><pre className="whitespace-pre-wrap text-sm">{JSON.stringify(JSON.parse(h.details),null,2)}</pre></details></li>)}</ul></div>
}
