"use client"
import Link from 'next/link'
import {useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {useGetPharmacyQueueQuery,useGetPharmacyLocationsQuery} from '@/store/api/pharmacyApiSlice'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card'
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table'
export default function PharmacyQueue(){
 const {user}=useAuth();const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [location,setLocation]=useState('');const [stage,setStage]=useState('');const {data:locations}=useGetPharmacyLocationsQuery()
 const {currentData,isFetching,isError,refetch}=useGetPharmacyQueueQuery({page,search,location_id:location?Number(location):undefined,stage:stage||undefined});const data=currentData?.data
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-bold text-primary">Pharmacy Operations</h1><p className="text-muted-foreground">Prescriptions, pharmacist review, fulfillment and PIP billing.</p></div>{['pharmacist','pharmacy_technician'].includes(user?.role||'')&&<Button asChild><Link href="/dashboard/pharmacy/new">Receive prescription</Link></Button>}</div>
 <div className="rounded-lg border bg-muted/30 p-4 text-sm">Internal pharmacy system · Development preview for synthetic records. Controlled-substance and compounded dispensing remain disabled while dedicated controls are built. Payer, MAPS and AI connections are not configured.</div>
 <div className="flex flex-wrap gap-4 items-center"><Link href="/dashboard/pharmacy/stock" className="underline">Locations and inventory</Link><label className="text-sm">Pharmacy location <select className="border rounded p-2 bg-background" value={location} onChange={e=>{setLocation(e.target.value);setPage(1)}}><option value="">All locations in my organization</option>{locations?.data.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label><label className="text-sm">Latest fill stage <select className="border rounded p-2 bg-background" value={stage} onChange={e=>{setStage(e.target.value);setPage(1)}}><option value="">All stages</option>{["intake","pending","ready","collected","delivered","cancelled"].map(s=><option key={s} value={s}>{s}</option>)}</select></label></div><Card><CardHeader><CardTitle>Prescription worklist</CardTitle></CardHeader><CardContent className="space-y-4"><Input aria-label="Search prescriptions" placeholder="Search prescription number or medication" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/>
 {isError?<p role="alert">Could not load prescriptions. <Button variant="outline" onClick={()=>refetch()}>Retry</Button></p>:isFetching?<p role="status">Loading prescriptions…</p>:<><Table><TableHeader><TableRow>{['Prescription / location','Patient / accident case','Medication','Latest fill','Coverage',''].map((s,i)=><TableHead key={i}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{data?.data.map(rx=><TableRow key={rx.id}><TableCell>{rx.rx_number}<div className="text-xs text-muted-foreground">{locations?.data.find(l=>l.id===rx.location_id)?.name}</div></TableCell><TableCell>{rx.first_name} {rx.last_name}<div className="text-muted-foreground text-xs">{rx.case_number}</div></TableCell><TableCell>{rx.medication} {rx.strength}<div className="text-xs">{Boolean(rx.controlled)&&"Controlled · "}{Boolean(rx.compounded)&&"Compounded"}</div></TableCell><TableCell>{rx.stage}<div className="text-xs">{rx.review_status?.replaceAll("_"," ")} · {rx.claim_status?.replaceAll("_"," ")}</div></TableCell><TableCell>{rx.coverage_status.replaceAll('_',' ')}</TableCell><TableCell><Link className="underline" href={`/dashboard/pharmacy/${rx.id}`}>Open {rx.rx_number}</Link></TableCell></TableRow>)}</TableBody></Table>{!data?.data.length&&<p>No prescriptions found. Receive a prescription to begin the pharmacy workflow.</p>}<div className="flex gap-4 items-center"><Button disabled={page===1} variant="outline" onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page} of {data?.last_page||1} · {data?.total||0} prescriptions</span><Button disabled={page>=(data?.last_page||1)} variant="outline" onClick={()=>setPage(page+1)}>Next</Button></div></>}
 </CardContent></Card></div>
}
