import { apiSlice, TAG_TYPES } from './apiSlice';
export type PrescriptionSource={id:number;original_name:string;mime_type:string;size:number;sha256:string;reference:string;created_by:number;created_at:string};
export type PharmacyPatient={id:number;record_number:string;first_name:string;last_name:string;date_of_birth:string;phone?:string;address?:string;version:number;clinical:Record<string,string|null>;history:{id:number;actor_id:number;created_at:string;details:Record<string,unknown>}[]};
export type PharmacyStaffData={staff:{id:number;first_name:string;last_name:string;role:string}[];assignments:{id:number;location_id:number;user_id:number;active:boolean;valid_until:string;version:number}[];history:{id:number;location_id:number;user_id:number;actor_id:number;created_at:string;details:string}[]};
export type PharmacyFill = {id:number;fill_number:number;version:number;quantity:string;stock_lot_id:number;days_supply:number;ndc:string;review_status:string;fulfillment_status:string;claim_status:string;invoice_id:number|null;invoice?:{invoice_number:string;amount:string;total_paid:string|null};review:Record<string,unknown>;fulfillment:Record<string,unknown>;claim:Record<string,unknown>};
export type PrescriptionLink={id:number;rx_number:string;medication:string;reason:string;reference:string;created_by:number;created_at:string};
export type PharmacyRx = {reserved_batches:{id:number;batch_number:string}[];replacement:PrescriptionLink|null;replaces:PrescriptionLink|null;discontinued_at:string|null;discontinued_by:number|null;discontinuation_reason:string|null;discontinuation_reference:string|null;id:number;rx_number:string;medication:string;strength:string;dosage_form:string;directions:string;quantity:string;refills_authorized:number;written_on:string;expires_on:string;controlled:boolean;compounded:boolean;compound_type:"sterile"|"nonsterile"|null;quantity_unit:string;location:{id:number;name:string;address:string};prescriber_name:string;source_reference:string;episode:{pharmacy_patient_id?:number|null;id:number;version:number;coverage_status:string;coverage:Record<string,unknown>};patient:{first_name:string;last_name:string};case:{case_number:string;accident_date:string};fills:PharmacyFill[];events:{id:number;action:string;actor_id:number;created_at:string;details:Record<string,unknown>}[]};
export type PharmacyLot={id:number;location_id:number;ndc:string;medication:string;lot_number:string;quantity_unit:string;expires_on:string;on_hand:string;reserved:string;status:string;version:number;receipt_reference:string};
export type CompoundIngredient={key:string;name:string;quantity:string;unit:string;specification:string};
export type CompoundFormula={id:number;code:string;revision:number;name:string;preparation_type:string;hazardous:boolean;status:string;version:number;created_by:number;record:{strength:string;dosage_form:string;output_quantity:string;output_unit:string;source_reference:string;method:string;quality_checks:string;storage:string;bud_basis:string;aseptic_process?:string;hazard_controls?:string;ingredients:CompoundIngredient[]};events:{id:number;action:string;actor_id:number;created_at:string;details:string}[]};
export type IngredientCount={id:number;created_by:number;recorded_quantity:string;counted_quantity:string;lot_version:number;reason:string;evidence:string;status:string;reviewed_by:number|null;review_evidence:string|null;reviewed_at:string|null;created_at:string};
export type IngredientLot={recall_reference:string|null;recall_evidence:string|null;recalled_by:number|null;recalled_at:string|null;trace:{batch_id:number;batch_number:string;ingredient_key:string;quantity:string;status:string}[];counts:IngredientCount[];id:number;location_id:number;ingredient_name:string;supplier:string;lot_number:string;quantity_unit:string;expires_on:string;on_hand:string;reserved:string;status:string;version:number;specification:string;certificate_reference:string;receipt_reference:string;events:{id:number;action:string;quantity:string;actor_id:number;created_at:string;details:string;batch_id:number|null}[]};
export type ExecutionAddendum={id:number;created_by:number;section:string;statement:string;reason:string;evidence:string;execution_version:number;created_at:string};
export type BatchExecution={addenda:ExecutionAddendum[];id:number;created_by:number;version:number;status:string;record:{prepared_on:string;personnel_reference:string;equipment_reference:string;process_record_reference:string;quality_results_reference:string;yield_quantity:string;yield_unit:string;deviations:string;environment_reference?:string;hazard_control_reference?:string;ingredients:{key:string;quantity:string;unit:string;measurement_reference:string}[]}};
export type CompoundBatch={prescription_discontinued_at:string|null;execution:BatchExecution|null;output_status:string;allocations:{id:number;ingredient_lot_id:number;ingredient_key:string;quantity:string;status:string;lot_status:string;lot_expires_on:string;lot_number:string;quantity_unit:string}[];id:number;batch_number:string;location_id:number;prescription_id:number;formulation_id:number;status:string;version:number;created_by:number;production_release_enabled:false;formula:CompoundFormula;record:{planned_on:string;calculation_reference:string;prescription_match_reference:string;site_process_reference:string;ingredients:{key:string;supplier:string;lot:string;expires_on:string;quantity:string;unit:string;certificate_reference:string}[]};events:CompoundFormula['events']};
export const pharmacyApi=apiSlice.injectEndpoints({endpoints:(b)=>({
 getPrescriptionSources:b.query<{data:PrescriptionSource[]},number>({query:id=>`/pharmacy/prescriptions/${id}/sources`,providesTags:[TAG_TYPES.PHARMACY]}),
 addPrescriptionSource:b.mutation<{data:{id:number}},{id:number;body:FormData}>({query:({id,body})=>({url:`/pharmacy/prescriptions/${id}/sources`,method:'POST',body}),invalidatesTags:[TAG_TYPES.PHARMACY]}),
 getIngredientLots:b.query<{data:{data:IngredientLot[];last_page:number;total:number}},{page:number;search:string;location_id?:number;status?:string}>({query:params=>({url:'/pharmacy/ingredient-lots',params}),providesTags:[TAG_TYPES.PHARMACY]}),
 getIngredientLot:b.query<{data:IngredientLot},number>({query:id=>`/pharmacy/ingredient-lots/${id}`,providesTags:[TAG_TYPES.PHARMACY]}),
 getCompoundFormulas:b.query<{data:{data:CompoundFormula[];last_page:number;total:number}},{page:number;search:string}>({query:params=>({url:'/pharmacy/formulations',params}),providesTags:[TAG_TYPES.PHARMACY]}),
 getCompoundFormula:b.query<{data:CompoundFormula},number>({query:id=>`/pharmacy/formulations/${id}`,providesTags:[TAG_TYPES.PHARMACY]}),
 getCompoundBatches:b.query<{data:{data:CompoundBatch[];last_page:number;total:number}},number>({query:page=>({url:'/pharmacy/batch-worksheets',params:{page}}),providesTags:[TAG_TYPES.PHARMACY]}),
 getCompoundBatch:b.query<{data:CompoundBatch},number>({query:id=>`/pharmacy/batch-worksheets/${id}`,providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyStaff:b.query<{data:PharmacyStaffData},void>({query:()=>'/pharmacy/staff',providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyPatients:b.query<{data:{data:PharmacyPatient[];total:number;last_page:number}},{search?:string;page?:number;location_id?:number}>({query:params=>({url:'/pharmacy/patients',params}),providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyPatient:b.query<{data:PharmacyPatient},number>({query:id=>`/pharmacy/patients/${id}`,providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyLocations:b.query<{data:{id:number;name:string;address:string;license_reference:string;active:boolean}[]},void>({query:()=>'/pharmacy/locations',providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyStock:b.query<{data:{data:PharmacyLot[];total:number;last_page:number}},{location_id?:number;search?:string;page?:number}>({query:params=>({url:'/pharmacy/stock',params}),providesTags:[TAG_TYPES.PHARMACY]}),
 pharmacyStockAction:b.mutation<{data:{id:number}},{path:string;body:Record<string,unknown>;method?:string}>({query:({path,body,method})=>({url:`/pharmacy/${path}`,body,method:method||'POST'}),invalidatesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyCases:b.query<{data:{id:number;case_number:string;title:string;accident_date:string|null;patients:{id:number;first_name:string;last_name:string}[]}[]},void>({query:()=>'/pharmacy/cases'}),
 getPharmacyQueue:b.query<{data:{data:{id:number;open_fill_count:number;reserved_batch_count:number;discontinued_at:string|null;rx_number:string;medication:string;strength:string;coverage_status:string;stage:string;review_status:string|null;claim_status:string|null;location_id:number;controlled:boolean;compounded:boolean;compound_type:"sterile"|"nonsterile"|null;first_name:string;last_name:string;case_number:string}[];current_page:number;last_page:number;total:number}},{page:number;search:string;location_id?:number;stage?:string;status?:string;replacement_for?:number;attention?:string}>({query:p=>({url:'/pharmacy/prescriptions',params:p}),providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyRx:b.query<{data:PharmacyRx},number>({query:id=>`/pharmacy/prescriptions/${id}`,providesTags:[TAG_TYPES.PHARMACY]}),
 createPharmacyRx:b.mutation<{data:{id:number}},Record<string,unknown>>({query:body=>({url:'/pharmacy/prescriptions',method:'POST',body}),invalidatesTags:[TAG_TYPES.PHARMACY]}),
 pharmacyAction:b.mutation<{data:PharmacyRx},{id:number;path:string;body:Record<string,unknown>;method?:string}>({query:({id,path,body,method})=>({url:`/pharmacy/prescriptions/${id}/${path}`,method:method||'POST',body}),invalidatesTags:[TAG_TYPES.PHARMACY,TAG_TYPES.INVOICE]}),
 getPharmacyAssistant:b.query<{data:{ai_connected:boolean;message:string;checks:{message:string;source:string}[]}},number>({query:id=>`/pharmacy/prescriptions/${id}/assistant`,providesTags:[TAG_TYPES.PHARMACY]})
})});
export const {useGetPrescriptionSourcesQuery,useAddPrescriptionSourceMutation,useGetIngredientLotsQuery,useGetIngredientLotQuery,useGetCompoundFormulasQuery,useGetCompoundFormulaQuery,useGetCompoundBatchesQuery,useGetCompoundBatchQuery,useGetPharmacyStaffQuery,useGetPharmacyPatientsQuery,useGetPharmacyPatientQuery,useGetPharmacyLocationsQuery,useGetPharmacyStockQuery,usePharmacyStockActionMutation,useGetPharmacyCasesQuery,useGetPharmacyQueueQuery,useGetPharmacyRxQuery,useCreatePharmacyRxMutation,usePharmacyActionMutation,useGetPharmacyAssistantQuery}=pharmacyApi;
