import { apiSlice, TAG_TYPES } from './apiSlice';
export type PharmacyPatient={id:number;record_number:string;first_name:string;last_name:string;date_of_birth:string;phone?:string;address?:string;version:number;clinical:Record<string,string|null>;history:{id:number;actor_id:number;created_at:string;details:Record<string,unknown>}[]};
export type PharmacyStaffData={staff:{id:number;first_name:string;last_name:string;role:string}[];assignments:{id:number;location_id:number;user_id:number;active:boolean;valid_until:string;version:number}[];history:{id:number;location_id:number;user_id:number;actor_id:number;created_at:string;details:string}[]};
export type PharmacyFill = {id:number;fill_number:number;version:number;quantity:string;stock_lot_id:number;days_supply:number;ndc:string;review_status:string;fulfillment_status:string;claim_status:string;invoice_id:number|null;invoice?:{invoice_number:string;amount:string;total_paid:string|null};review:Record<string,unknown>;fulfillment:Record<string,unknown>;claim:Record<string,unknown>};
export type PharmacyRx = {id:number;rx_number:string;medication:string;strength:string;dosage_form:string;directions:string;quantity:string;refills_authorized:number;written_on:string;expires_on:string;controlled:boolean;compounded:boolean;compound_type:"sterile"|"nonsterile"|null;quantity_unit:string;location:{id:number;name:string;address:string};prescriber_name:string;source_reference:string;episode:{pharmacy_patient_id?:number|null;id:number;version:number;coverage_status:string;coverage:Record<string,unknown>};patient:{first_name:string;last_name:string};case:{case_number:string;accident_date:string};fills:PharmacyFill[];events:{id:number;action:string;actor_id:number;created_at:string;details:Record<string,unknown>}[]};
export type PharmacyLot={id:number;location_id:number;ndc:string;medication:string;lot_number:string;quantity_unit:string;expires_on:string;on_hand:string;reserved:string;status:string;version:number;receipt_reference:string};
export const pharmacyApi=apiSlice.injectEndpoints({endpoints:(b)=>({
 getPharmacyStaff:b.query<{data:PharmacyStaffData},void>({query:()=>'/pharmacy/staff',providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyPatients:b.query<{data:{data:PharmacyPatient[];total:number;last_page:number}},{search?:string;page?:number;location_id?:number}>({query:params=>({url:'/pharmacy/patients',params}),providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyPatient:b.query<{data:PharmacyPatient},number>({query:id=>`/pharmacy/patients/${id}`,providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyLocations:b.query<{data:{id:number;name:string;address:string;license_reference:string;active:boolean}[]},void>({query:()=>'/pharmacy/locations',providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyStock:b.query<{data:{data:PharmacyLot[];total:number;last_page:number}},{location_id?:number;search?:string;page?:number}>({query:params=>({url:'/pharmacy/stock',params}),providesTags:[TAG_TYPES.PHARMACY]}),
 pharmacyStockAction:b.mutation<{data:{id:number}},{path:string;body:Record<string,unknown>;method?:string}>({query:({path,body,method})=>({url:`/pharmacy/${path}`,body,method:method||'POST'}),invalidatesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyCases:b.query<{data:{id:number;case_number:string;title:string;accident_date:string|null;patients:{id:number;first_name:string;last_name:string}[]}[]},void>({query:()=>'/pharmacy/cases'}),
 getPharmacyQueue:b.query<{data:{data:{id:number;rx_number:string;medication:string;strength:string;coverage_status:string;stage:string;review_status:string|null;claim_status:string|null;location_id:number;controlled:boolean;compounded:boolean;compound_type:"sterile"|"nonsterile"|null;first_name:string;last_name:string;case_number:string}[];current_page:number;last_page:number;total:number}},{page:number;search:string;location_id?:number;stage?:string}>({query:p=>({url:'/pharmacy/prescriptions',params:p}),providesTags:[TAG_TYPES.PHARMACY]}),
 getPharmacyRx:b.query<{data:PharmacyRx},number>({query:id=>`/pharmacy/prescriptions/${id}`,providesTags:[TAG_TYPES.PHARMACY]}),
 createPharmacyRx:b.mutation<{data:{id:number}},Record<string,unknown>>({query:body=>({url:'/pharmacy/prescriptions',method:'POST',body}),invalidatesTags:[TAG_TYPES.PHARMACY]}),
 pharmacyAction:b.mutation<{data:PharmacyRx},{id:number;path:string;body:Record<string,unknown>;method?:string}>({query:({id,path,body,method})=>({url:`/pharmacy/prescriptions/${id}/${path}`,method:method||'POST',body}),invalidatesTags:[TAG_TYPES.PHARMACY,TAG_TYPES.INVOICE]}),
 getPharmacyAssistant:b.query<{data:{ai_connected:boolean;message:string;checks:{message:string;source:string}[]}},number>({query:id=>`/pharmacy/prescriptions/${id}/assistant`,providesTags:[TAG_TYPES.PHARMACY]})
})});
export const {useGetPharmacyStaffQuery,useGetPharmacyPatientsQuery,useGetPharmacyPatientQuery,useGetPharmacyLocationsQuery,useGetPharmacyStockQuery,usePharmacyStockActionMutation,useGetPharmacyCasesQuery,useGetPharmacyQueueQuery,useGetPharmacyRxQuery,useCreatePharmacyRxMutation,usePharmacyActionMutation,useGetPharmacyAssistantQuery}=pharmacyApi;
