"use client"
import Link from 'next/link'
import {FillLabels} from '@/components/pharmacy/fill-labels'
import {PrescriptionReplacement} from '@/components/pharmacy/prescription-replacement'
import {AllowanceCorrections} from '@/components/pharmacy/allowance-corrections'
import {PrescriptionQuantity} from '@/components/pharmacy/prescription-quantity'
import {PrescriptionSources} from '@/components/pharmacy/prescription-sources'
import {useParams} from 'next/navigation'
import {useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {useGetPharmacyRxQuery,usePharmacyActionMutation,useGetPharmacyAssistantQuery,PharmacyFill,useGetPharmacyStockQuery} from '@/store/api/pharmacyApiSlice'
import {Field,Choice,errorMessage} from '@/components/pharmacy/fields'
import {Button} from '@/components/ui/button'
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card'
const label=(s:string)=>s.replaceAll('_',' ')
const actionLabels:Record<string,string>={approve:'Approve pharmacist review',hold:'Place fill on hold',cancel:'Cancel fill',ready:'Confirm final check',collected:'Record pickup',delivered:'Record delivery',prepare_claim:'Prepare billing draft',record_submission:'Record external submission',record_denial:'Record payer issue',record_maps:'Record MAPS confirmation'}
const actionLabel=(s:string)=>actionLabels[s]||label(s)
export default function PrescriptionDetail(){
 const id=Number(useParams().id);const {user}=useAuth();const role=user?.role||'';const {currentData,isFetching,isError,refetch}=useGetPharmacyRxQuery(id);const rx=currentData?.data;const {data:assistant,isFetching:checkingRecords,isError:recordCheckError}=useGetPharmacyAssistantQuery(id);const [mutate,{isLoading}]=usePharmacyActionMutation();const [error,setError]=useState('');const [success,setSuccess]=useState('');const [fillKey,setFillKey]=useState(()=>crypto.randomUUID());const [stopKey]=useState(()=>crypto.randomUUID());
 async function save(path:string,body:Record<string,unknown>,method?:string){setError('');setSuccess('');try{await mutate({id,path,body,method}).unwrap();setSuccess('Saved. The record and history have been updated.');if(path==='fills')setFillKey(crypto.randomUUID())}catch(e){setError(errorMessage(e))}}
 if(isError)return <p role="alert">Could not open this prescription. <Button onClick={()=>refetch()}>Retry</Button></p>
 if(!rx)return <p role="status">Loading prescription…</p>
 const openFill=rx.fills.some(f=>!["collected","delivered","cancelled"].includes(f.fulfillment_status));const fillsRemain=rx.quantity_balance.next_authorization_number!==null
 return <div className="space-y-6"><Link href="/dashboard/pharmacy" className="underline">Back to pharmacy</Link><div>{rx.episode.pharmacy_patient_id&&['pharmacist','pharmacy_technician'].includes(user?.role||'')&&<Link className="underline block" href={`/dashboard/pharmacy/patients/${rx.episode.pharmacy_patient_id}`}>Review patient clinical record</Link>}<h1 className="text-3xl font-bold text-primary">{rx.rx_number} · {rx.medication}</h1>{Boolean(rx.compounded)&&<p className="font-semibold">Compounding: {rx.compound_type==='sterile'?'Sterile':rx.compound_type==='nonsterile'?'Nonsterile':'Classification requires review'} · Production and dispensing controls pending</p>}<p>{rx.patient.first_name} {rx.patient.last_name} · {rx.case.case_number} · Accident {rx.case.accident_date?.slice(0,10)} · {rx.location.name}</p></div>
 <div className="rounded border p-4 text-sm">Internal pharmacy development preview · Synthetic records only. Stock is reserved for each fill and deducted on handover. No prescription, payer or MAPS transmission is performed. Controlled and compounded dispensing remain disabled.</div>
 {error&&<p role="alert" className="text-destructive">{error}</p>}{success&&<p role="status">{success}</p>}
 {rx.discontinued_at?<div role="status" className="border border-destructive rounded p-4 space-y-2"><h2 className="font-semibold">Prescription discontinued</h2><p>{rx.discontinuation_reason}</p><p>Authority / evidence: {rx.discontinuation_reference}</p><p className="text-sm">Recorded {rx.discontinued_at} · Pharmacist #{rx.discontinued_by}. Future fills, preparation and handover are blocked. Cancel any open fill and release unused batch reservations separately. Completed history is retained.</p></div>:role==='pharmacist'&&<details className="border rounded p-4"><summary className="cursor-pointer underline">Discontinue prescription</summary><form className="grid gap-3 mt-3" onSubmit={e=>{e.preventDefault();save('discontinue',{...Object.fromEntries(new FormData(e.currentTarget)),request_id:stopKey})}}><p className="text-sm">Record the pharmacist’s decision and its supporting authority. This immediately stops future fills, preparation and handover. It does not notify the prescriber or patient, cancel open fills, or return stock. There is no reactivation action.</p><Field name="reason" label="Reason for discontinuation" maxLength={2000}/><Field name="reference" label="Prescriber instruction / supporting authority reference" maxLength={2000}/><label className="flex gap-2 text-sm"><input type="checkbox" required/>I have reviewed the supporting evidence and will resolve outstanding fills and batch reservations.</label><Button disabled={isLoading||isFetching} variant="destructive">Record discontinuation</Button></form></details>}
 {rx.discontinued_at&&(rx.fills.some(f=>['pending','ready'].includes(f.fulfillment_status))||rx.reserved_batches.length>0)&&<Card><CardHeader><CardTitle>Outstanding work after discontinuation</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm">A pharmacist must explicitly cancel open fills and release unused ingredient reservations. These actions resolve reservations; they do not record a physical return, disposal or notification.</p>{rx.fills.filter(f=>['pending','ready'].includes(f.fulfillment_status)).map(f=><p key={`open-fill-${f.id}`}><a className="underline" href={`#fill-${f.id}`}>Open fill {f.fill_number} · {f.fulfillment_status} · {f.quantity} units reserved</a></p>)}{rx.reserved_batches.map(b=><p key={`reserved-batch-${b.id}`}>{['pharmacist','pharmacy_technician'].includes(role)?<Link className="underline" href={`/dashboard/pharmacy/compounding?view=batch&id=${b.id}`}>Resolve ingredient reservation · {b.batch_number}</Link>:<span>Batch {b.batch_number} has reserved ingredients; assigned pharmacy staff must resolve it.</span>}</p>)}</CardContent></Card>}
 <PrescriptionReplacement key={`replacement-${user?.id}-${id}`} rx={rx} role={role}/>
 <Card><CardHeader><CardTitle>Prescription received</CardTitle></CardHeader><CardContent><dl className="grid gap-3 md:grid-cols-2"><div><dt>Medication</dt><dd>{rx.medication} {rx.strength} · {rx.dosage_form}</dd></div><div><dt>Directions</dt><dd>{rx.directions}</dd></div><div><dt>Quantity / refills</dt><dd>{rx.quantity} {rx.quantity_unit} / {rx.refills_authorized}</dd></div><div><dt>Prescriber</dt><dd>{rx.prescriber_name}</dd></div><div><dt>Written / expires</dt><dd>{rx.written_on} / {rx.expires_on}</dd></div><div><dt>Source reference</dt><dd>{rx.source_reference}</dd></div></dl></CardContent></Card>
 {['pharmacist','pharmacy_technician'].includes(role)&&<PrescriptionSources key={`${user?.id}-${id}`} id={id}/>}
 <Card><CardHeader><CardTitle>Accident coverage · {label(rx.episode.coverage_status)}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm">Shared across this patient’s prescriptions for this accident. Verification records evidence; it does not guarantee payment or authorize dispensing.</p><dl className="grid gap-2 md:grid-cols-2">{Object.entries(rx.episode.coverage).map(([k,v])=><div key={k}><dt className="text-muted-foreground">{label(k)}</dt><dd>{String(v??'Not recorded')}</dd></div>)}</dl>
 {role!=='admin'&&<details><summary className="cursor-pointer underline">Update coverage evidence</summary><form key={rx.episode.version} className="grid gap-4 md:grid-cols-2 mt-4" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));save('coverage',{...d,limit:d.limit||null,version:rx.episode.version},'PUT')}}>
 <Choice name="status" label="Coverage status" options={['unverified','verified','disputed','exhausted','not_applicable']} defaultValue={rx.episode.coverage_status}/><Field name="payer" label="Payer" defaultValue={String(rx.episode.coverage.payer||'')}/><Field name="claim_number" label="Claim number" required={false} defaultValue={String(rx.episode.coverage.claim_number||'')}/><Field name="policy_number" label="Policy number" required={false} defaultValue={String(rx.episode.coverage.policy_number||'')}/><Field name="adjuster" label="Adjuster / contact reference" required={false} defaultValue={String(rx.episode.coverage.adjuster||'')}/><Field name="coordination" label="Coordination of benefits findings" defaultValue={String(rx.episode.coverage.coordination||'')}/><Field name="verified_on" label="Evidence checked on" type="date"/><Field name="limit" label="Confirmed limit (blank if unknown)" type="number" step="0.01" min="0" required={false} defaultValue={String(rx.episode.coverage.limit??'')}/><Field name="evidence" label="Evidence reference and verification note"/><Button disabled={isLoading||isFetching}>Save coverage evidence</Button></form></details>}</CardContent></Card>
 <PrescriptionQuantity key={`quantity-${user?.id}-${id}`} rx={rx} role={role} disabled={isLoading||isFetching} save={d=>save('allowances/close',d)}/>

 <AllowanceCorrections key={`allowance-corrections-${user?.id}-${id}-${rx.quantity_balance.ledger_token}`} rx={rx} role={role} userId={Number(user?.id)}/>
 <Card><CardHeader><CardTitle>Fills and billing</CardTitle></CardHeader><CardContent className="space-y-5">{!rx.fills.length&&<p>No fills recorded. Each fill receives its own review and billing history.</p>}{rx.fills.map(f=><FillCard key={`${f.id}-${f.version}-${rx.discontinued_at}-${f.stock_recall_reference}-${f.stock_status}-${f.stock_custody_hold}-${f.current_product?.id}`} rxId={id} fill={f} unit={rx.quantity_unit} stopped={Boolean(rx.discontinued_at)} role={role} controlled={Boolean(rx.controlled)} restricted={Boolean(rx.controlled)||Boolean(rx.compounded)} disabled={isLoading||isFetching} save={(d)=>save(`fills/${f.id}/actions`,{...d,version:f.version,product_id:f.current_product?.id||null,label_id:f.current_label?.id||null})}/>)}
 {['pharmacist','pharmacy_technician'].includes(role)&&(rx.quantity_balance.pending_correction_id?<p>New fills are held pending independent allowance-correction review.</p>:rx.discontinued_at?<p>No new fills: this prescription is discontinued.</p>:openFill?<p>Resolve the open fill before preparing another.</p>:!fillsRemain?<p>No authorized fills remain. Obtain a renewed prescription before further dispensing.</p>:<CreateFill key={fillKey} locationId={rx.location.id} unit={rx.quantity_unit} maximum={rx.quantity_balance.available_quantity} partials={rx.quantity_balance.mode==="quantity"} disabled={isLoading||isFetching} save={d=>save('fills',{...d,request_id:fillKey})}/>) }</CardContent></Card>
 <Card><CardHeader><CardTitle>Assistant readiness</CardTitle></CardHeader><CardContent className="space-y-3"><p>{recordCheckError?'Record checks are unavailable. Review the saved records directly.':checkingRecords?'Refreshing record checks…':assistant?.data.message||'Record checks are loading.'}</p>{!checkingRecords&&!recordCheckError&&assistant?.data.checks.map((x,i)=><p key={i}>{x.message} <span className="text-xs text-muted-foreground">Source: {x.source}</span></p>)}<p className="text-sm text-muted-foreground">Planned AI support: extract prescription information with source references, identify missing evidence and draft correspondence for review. Patient data is not sent to an AI provider.</p></CardContent></Card>
 <Card><CardHeader><CardTitle>Action history</CardTitle></CardHeader><CardContent><ol className="space-y-3">{rx.events.map(e=><li key={e.id}><strong>{label(e.action)}</strong> · {e.created_at} · Staff #{e.actor_id}<details><summary className="text-sm underline cursor-pointer">Recorded evidence</summary><pre className="whitespace-pre-wrap break-words text-xs p-3 bg-muted rounded">{JSON.stringify(e.details,null,2)}</pre></details></li>)}</ol></CardContent></Card></div>
}
function FillCard({rxId,fill:f,unit,stopped,role,controlled,restricted,disabled,save}:{rxId:number;fill:PharmacyFill;unit:string;stopped:boolean;role:string;controlled:boolean;restricted:boolean;disabled:boolean;save:(d:Record<string,unknown>)=>void}){
 const complete=['collected','delivered','cancelled'].includes(f.fulfillment_status);let actions:string[]=[]
 if(role==='pharmacist'&&!complete)actions=(stopped||Boolean(f.stock_recall_reference)||Boolean(f.stock_custody_hold))?['cancel']:f.stock_status==='quarantined'?(f.fulfillment_status==='pending'?['hold','cancel']:['cancel']):restricted?['hold','cancel']:f.fulfillment_status==='pending'?['approve','hold','cancel',...(f.review_status==='approved'?['ready']:[])]:['collected','delivered','cancel']
 if(role==='medical_biller'&&['collected','delivered'].includes(f.fulfillment_status))actions=!f.invoice_id?['prepare_claim']:f.claim_status==='submitted_externally'?['record_denial']:['record_submission']
 if(role==='pharmacist'&&controlled&&['collected','delivered'].includes(f.fulfillment_status))actions=['record_maps'];
 const [action,setAction]=useState(actions[0]||'');const fulfillment=['collected','delivered'].includes(action)
 return <div id={`fill-${f.id}`} className="rounded-lg border p-4 space-y-3"><h3 className="font-semibold">Fill {f.fill_number} · NDC {f.ndc}</h3><p>Stock receipt #{f.stock_lot_id} · {f.quantity} {unit} · {f.days_supply} days</p><p>{f.authorization_number===null?"Historical / restricted allowance accounting":f.authorization_number===1?"Original allowance":`Refill ${f.authorization_number-1}`}</p>{f.partial_reason&&<p className="break-words">Partial supply reason: {f.partial_reason}</p>}<div className="flex flex-wrap gap-3 text-sm"><span>Review: {label(f.review_status)}</span><span>Fulfillment: {label(f.fulfillment_status)}</span><span>Claim: {label(f.claim_status)}</span></div>
 {['pharmacist','pharmacy_technician'].includes(role)&&<section className="border rounded p-3 space-y-2 text-sm break-words"><Link className="underline" href={`/dashboard/pharmacy/stock/${f.stock_lot_id}`}>Review verified stock product</Link>{f.current_product&&<p>Current product: revision {f.current_product.revision} · {f.current_product.brand_name?`${f.current_product.brand_name} (${f.current_product.generic_name})`:f.current_product.generic_name} · {f.current_product.strength} · {f.current_product.dosage_form} · {f.current_product.manufacturer}</p>}{f.reviewed_product?<p>Product retained at review: revision {f.reviewed_product.revision} · {f.reviewed_product.brand_name||f.reviewed_product.generic_name} · {f.reviewed_product.strength} · {f.reviewed_product.dosage_form} · {f.reviewed_product.manufacturer}</p>:<p>No verified product retained at review.</p>}{!complete&&(!f.current_product||f.current_product.id!==f.reviewed_product?.id)&&<p role="status">{f.current_product?'Product verification needs a fresh pharmacist review. Review pending fills again; cancel prepared fills and start again.':'Receipt product verification is required before fill approval.'}</p>}</section>}
 {['pharmacist','pharmacy_technician'].includes(role)&&<FillLabels rxId={rxId} fill={f} role={role} restricted={restricted} disabled={disabled}/>}
 {f.stock_custody_hold&&!f.stock_recall_reference&&<div className="border border-destructive rounded p-3 space-y-2"><p className="font-semibold">Stock custody hold</p><p>{f.stock_custody_hold}</p>{['pharmacist','pharmacy_technician'].includes(role)&&<Link className="underline" href={`/dashboard/pharmacy/stock/${f.stock_lot_id}`}>Investigate stock custody</Link>}</div>}
 {f.stock_status==='quarantined'&&!f.stock_recall_reference&&<div className="border rounded p-3 space-y-2"><p className="font-semibold">Stock receipt quarantined</p><p>Preparation and handover are blocked while this receipt is quarantined. Review the receipt and resolve any pending count discrepancy before releasing stock.</p>{['pharmacist','pharmacy_technician'].includes(role)&&<Link className="underline" href={`/dashboard/pharmacy/stock/${f.stock_lot_id}`}>Review stock quarantine and counts</Link>}</div>}
 {f.stock_recall_reference&&<div className="border border-destructive rounded p-3 space-y-2 break-words"><p className="font-semibold">Stock recall hold: {f.stock_recall_reference}</p><p>This receipt cannot be prepared or handed over. Resolve open reservations by cancelling the fill; completed history is retained for follow-up.</p>{['pharmacist','pharmacy_technician'].includes(role)&&<Link className="underline" href={`/dashboard/pharmacy/stock/${f.stock_lot_id}`}>Review stock recall and trace</Link>}</div>}
 {f.invoice&&<p>Invoice {f.invoice.invoice_number} · Billed ${f.invoice.amount} · Recorded receipts ${f.invoice.total_paid||'0.00'} {role==='medical_biller'&&<Link className="underline" href="/dashboard/billing/payments">Open payment ledger</Link>}</p>}
 {Object.keys(f.claim).length>0&&<details><summary className="underline cursor-pointer text-sm">Claim evidence</summary><pre className="whitespace-pre-wrap break-words text-xs">{JSON.stringify(f.claim,null,2)}</pre></details>}
 {restricted&&<p className="text-sm">Controlled or compounded dispensing is not yet enabled. This fill can be held or cancelled.</p>}{actions.length>0&&<form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();const entries=Object.fromEntries(new FormData(e.currentTarget));const checks=Object.fromEntries(Object.entries(entries).filter(([k])=>k.startsWith('check_')).map(([k,v])=>[k.slice(6),v==='on']));save({...Object.fromEntries(Object.entries(entries).filter(([k])=>!k.startsWith('check_'))),action,checks})}}><label className="grid gap-1 text-sm">Next action<select className="border rounded h-10 px-3 bg-background" value={action} onChange={e=>setAction(e.target.value)}>{actions.map(a=><option key={a} value={a}>{actionLabel(a)}</option>)}</select></label><Field name="note" label="Action note / review findings"/>
 {action==='approve'&&<fieldset className="md:col-span-2 space-y-2"><legend className="font-medium">Pharmacist review</legend>{[['identity','Patient identity and prescription source checked'],['prescriber','Prescriber authority and prescription validity checked'],['therapy','Allergies, interactions, duplicate therapy and dosing reviewed'],['product','Selected stock, medication, strength, NDC and quantity checked']].map(([k,l])=><label key={k} className="flex gap-2 items-start text-sm"><input type="checkbox" name={`check_${k}`} required/>{l}</label>)}<p className="text-xs text-muted-foreground">Records your professional review. No automated clinical database check is available.</p></fieldset>}
 {action==='ready'&&<label className="flex gap-2 items-start text-sm md:col-span-2"><input type="checkbox" name="check_label" required/>Final product and label verified by pharmacist</label>}
 {action==='record_maps'&&<Field name="maps_reference" label="External MAPS submission confirmation"/>}
 {(fulfillment||action==='record_submission')&&<Field name="occurred_on" label={fulfillment?'Fulfillment date':'External submission date'} type="date"/>}
 {(fulfillment||['prepare_claim','record_submission','record_denial'].includes(action))&&<Field name="reference" label={action==='prepare_claim'?'Pricing basis reference':'Evidence / confirmation reference'}/>}
 {fulfillment&&<Choice name="counseling" label="Counseling outcome" options={['provided','declined','documented_remote']}/>}
 {fulfillment&&controlled&&<><Choice name="maps_status" label="MAPS reporting status" options={['pending','submitted']}/><Field name="maps_reference" label="MAPS confirmation (required if submitted)" required={false}/></>}
 {action==='prepare_claim'&&<Field name="amount" label="Billed amount (not an automatic fee calculation)" type="number" min="0.01" step="0.01"/>}
 {action==='record_denial'&&<><Choice name="denial_type" label="Issue classification" options={['coverage','coding','medical_necessity','cost','no_response']}/><Field name="determination_on" label="Written determination date (not required for no response)" type="date" required={false}/></>}
 <Button disabled={disabled} className="md:col-span-2">{actionLabel(action)}</Button></form>}</div>
}

function CreateFill({locationId,unit,maximum,partials,disabled,save}:{locationId:number;unit:string;maximum:string;partials:boolean;disabled:boolean;save:(d:Record<string,unknown>)=>void}){
 const [quantity,setQuantity]=useState('');const isPartial=partials&&Number(quantity)>0&&Number(quantity)<Number(maximum)
 const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [lotId,setLotId]=useState('');const {currentData,isFetching,isError}=useGetPharmacyStockQuery({location_id:locationId,search,page});const lot=currentData?.data.data.find(l=>String(l.id)===lotId)
 return <details><summary className="cursor-pointer underline">Create fill and reserve stock</summary><div className="space-y-3 mt-4"><label className="grid gap-1 text-sm">Find stock by NDC or medication<input className="border rounded p-2 bg-background" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);setLotId('')}}/></label>{isError&&<p role="alert">Stock could not be loaded.</p>}<div className="flex gap-3"><Button variant="outline" disabled={page===1||isFetching} onClick={()=>{setPage(page-1);setLotId('')}}>Previous stock</Button><span>Page {page} of {currentData?.data.last_page||1}</span><Button variant="outline" disabled={page>=(currentData?.data.last_page||1)||isFetching} onClick={()=>{setPage(page+1);setLotId('')}}>Next stock</Button></div>
 <form className="grid gap-4 md:grid-cols-2" onSubmit={e=>{e.preventDefault();if(lot)save({...Object.fromEntries(new FormData(e.currentTarget)),stock_lot_id:lot.id,ndc:lot.ndc})}}><label className="grid gap-1 text-sm md:col-span-2">Stock at this pharmacy<select className="border rounded p-2 bg-background" required value={lotId} onChange={e=>setLotId(e.target.value)}><option value="">Select stock receipt and lot</option>{currentData?.data.data.map(l=><option key={l.id} value={l.id} disabled={Boolean(l.custody_hold)||l.status!=='available'||l.quantity_unit!==unit||Number(l.on_hand)<=Number(l.reserved)}>{l.medication} · {l.ndc} · Lot {l.lot_number} · Expires {l.expires_on} · Available {(Number(l.on_hand)-Number(l.reserved)).toFixed(3)} {l.quantity_unit} · {l.custody_hold?'custody hold':l.status}</option>)}</select></label><Field name="quantity" label={`Planned quantity (${unit}; remaining ${maximum})`} type="number" min="0.001" max={maximum} step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)}/>{partials&&<Field name="partial_reason" label="Partial supply reason (required when leaving a remainder)" required={isPartial} maxLength={2000}/>}<Field name="days_supply" label="Days’ supply" type="number" min="1" max="365"/><Button disabled={disabled||isFetching||!lot||Boolean(lot.custody_hold)}>Reserve stock for review</Button><Link className="underline" href="/dashboard/pharmacy/stock">Receive stock</Link></form></div></details>
}
