"use client"
import Link from 'next/link'
import {useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {useGetStockTransfersQuery,useGetStockTransferDestinationsQuery} from '@/store/api/pharmacyApiSlice'
import {Button} from '@/components/ui/button'
export default function Transfers(){
 const {user}=useAuth();const allowed=['pharmacist','pharmacy_technician'].includes(user?.role||'');const [page,setPage]=useState(1);const [status,setStatus]=useState('')
 const {currentData,isFetching,isError,refetch}=useGetStockTransfersQuery({page,status:status||undefined},{skip:!allowed});const {data:sites}=useGetStockTransferDestinationsQuery(undefined,{skip:!allowed});const name=(id:number)=>sites?.data.find(l=>l.id===id)?.name||`Location #${id}`
 if(!allowed)return <p>Pharmacy staff access is required.</p>
 return <div className="space-y-5 min-w-0"><Link className="underline" href="/dashboard/pharmacy/stock">Back to inventory</Link><h1 className="text-3xl font-bold text-primary">Stock transfers</h1><p>Synthetic preview. Open a stock receipt to plan a transfer. Dispatch and independent receipt are separate steps; received stock stays quarantined until reviewed.</p><label className="grid gap-1 text-sm">Transfer status<select className="border rounded p-2 bg-background" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{['planned','dispatched','received','received_corrected','received_discrepancy','cancelled'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label>{isError?<p role="alert">Transfers could not be loaded. <Button variant="outline" onClick={()=>refetch()}>Retry</Button></p>:isFetching?<p role="status">Loading transfers…</p>:<div className="space-y-3">{currentData?.data.data.map(t=><div key={t.id} className="border rounded p-4 space-y-2 break-words"><Link className="underline font-semibold" href={`/dashboard/pharmacy/transfers/${t.id}`}>Transfer #{t.id} · {t.product.medication}</Link><p>{name(t.source_location_id)} → {name(t.destination_location_id)}</p><p>{t.quantity} {t.product.quantity_unit} · {t.status.replaceAll('_',' ')}{t.received_quantity!==null?` · Originally received ${t.received_quantity}`:''}{t.corrected_received_quantity!==null?` · Corrected receipt ${t.corrected_received_quantity}`:''}</p></div>)}{!currentData?.data.data.length&&<p>No transfers match this view.</p>}</div>}<div className="flex flex-wrap gap-3 items-center"><Button variant="outline" disabled={isFetching||page===1} onClick={()=>setPage(page-1)}>Previous transfers</Button><span>Page {page} of {currentData?.data.last_page||1}</span><Button variant="outline" disabled={isFetching||page>=(currentData?.data.last_page||1)} onClick={()=>setPage(page+1)}>Next transfers</Button></div></div>
}
