import { Skeleton } from "antd";

import { Star } from "lucide-react";
import Slider from "react-slick";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import FadeInOnScroll from "../../shared/effects/in-view";
import { useGetTestimonialsQuery } from "../../../redux/features/testimonialApiSlice";

const Testmonials = () => {
  const testimonials = [
    {
      text: "I love how easy it is to use this website. Even as someone who is not particularly tech-savvy, I was able to navigate it with ease. The analytics provided are comprehensive and insightful.",
      name: "Sophia Davis",
      role: "CEO, Unity Analytics",
    },
    {
      text: "I stumbled upon this tool and was blown away by the analytics and insights it provided. The interface is user-friendly, and the data is presented in a visually appealing way. Highly recommend!",
      name: "Liam Martinez",
      role: "Marketing Manager",
    },
    {
      text: "I have tried several analytics websites, but this one is by far the best. The data is presented in a concise manner, and the insights helped me make better business decisions. Thank you!",
      name: "James Carter",
      role: "COO, Digital Corp",
    },
    {
      text: "The analytics provided are comprehensive and insightful, and I have already recommended it to several of my colleagues.",
      name: "Sophia Davis",
      role: "CEO, Unity Analytics",
    },
    {
      text: "I'm a data junkie, and I've tried countless analytics websites over the years. But this website is easily one of the best I've come across. The analytics are comprehensive and detailed.",
      name: "Benjamin Evans",
      role: "Data Scientist",
    },
    {
      text: "As a small business owner, I have to say the data generated by my website has been a game-changer for me. The metrics are presented in such a clear and concise manner.",
      name: "Olivia Foster",
      role: "Founder, StartUp Hub",
    },
  ];

  const { data: testimonialsRes, isLoading: isLoadingTestimonials } =
    useGetTestimonialsQuery();
  const apiTestimonials = testimonialsRes?.testimonials?.data || [];
  const rawTestimonials =
    apiTestimonials.length > 0 ? apiTestimonials : testimonials;
  const testimonialsData = rawTestimonials.map((item) => ({
    comment: item.comment ?? item.text,
    commented_by: item.commented_by ?? item.name,
    position: item.position ?? item.role,
    rating: item.rating ?? 5,
  }));


  const settings = {
    dots: true,
    infinite: true,
    autoplay: true, // auto slide on
    autoplaySpeed: 4000,
    speed: 500,
    slidesToShow: 1, // ek shathe ek grid page dekhabe
    slidesToScroll: 1,
    arrows: true,
  };

  return (
    <div className="mt-[100px] overflow-hidden px-6">
      {isLoadingTestimonials ? (
        <Skeleton />
      ) : (
        <Slider {...settings}>
          <div>
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">
              {testimonialsData?.map((item, index) => (
                <FadeInOnScroll
                  key={index}
                  className="bg-gray-50 border border-[#0C93AA99]  rounded-xl p-6 hover:shadow-lg transition"
                >
                  {/* Stars */}
                  <div className="flex mb-4">
                    {[...Array(Number(item?.rating || 5))].map((_, i) => (
                      <Star
                        key={i}
                        size={20}
                        className="fill-[#103E46] text-[#103E46]"
                      />
                    ))}
                  </div>
                  {/* Text */}
                  <p className="text-[#103E46] text-[16px] leading-[150%]">
                    {item.comment}
                  </p>
                  {/* Name + Role */}
                  <div className="mt-6">
                    <p className="text-[#004652] font-semibold">
                      {item.commented_by}
                    </p>
                    <p className="text-sm text-[#00000080]">{item.position}</p>
                  </div>
                </FadeInOnScroll>
              ))}
            </div>
          </div>
        </Slider>
      )}
    </div>
  );
};

export default Testmonials;
