"use client"
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import Link from 'next/link'
import {useGetPharmacyCasesQuery,useCreatePharmacyRxMutation,useGetPharmacyLocationsQuery,useGetPharmacyPatientsQuery} from '@/store/api/pharmacyApiSlice'
import {Field,Choice,errorMessage} from '@/components/pharmacy/fields'
import {Button} from '@/components/ui/button'
import {useAuth} from '@/hooks/useAuth'
export default function NewPrescription(){
 const router=useRouter();const {user}=useAuth();const {data,isError}=useGetPharmacyCasesQuery();const [caseId,setCaseId]=useState('');const [error,setError]=useState('');const [create,{isLoading}]=useCreatePharmacyRxMutation();const [key]=useState(()=>crypto.randomUUID());const {data:locations}=useGetPharmacyLocationsQuery();const selected=data?.data.find(c=>String(c.id)===caseId);const [locationId,setLocationId]=useState('');const [patientSearch,setPatientSearch]=useState('');const [patientMode,setPatientMode]=useState('chart');const [compounded,setCompounded]=useState(false);const {data:charts}=useGetPharmacyPatientsQuery({location_id:locationId?Number(locationId):undefined,search:patientSearch},{skip:!locationId})
 if(!['pharmacist','pharmacy_technician'].includes(user?.role||'')) return <p>Prescription intake is restricted to pharmacy staff.</p>
 return <div className="max-w-4xl space-y-5"><Link className="underline" href="/dashboard/pharmacy">Back to pharmacy</Link><h1 className="text-3xl font-bold text-primary">Receive prescription</h1><p>Record the prescription received by your pharmacy. Keep the original prescription securely and record its source reference below. This development preview is for synthetic records. This does not issue a prescription.</p>{isError&&<p role="alert">Case information could not be loaded.</p>}
 <form className="grid gap-5 md:grid-cols-2" onSubmit={async e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);const d=Object.fromEntries(f);try{const result=await create({...d,request_id:key,case_id:Number(caseId),patient_id:patientMode==='legacy'?Number(d.patient_id):undefined,pharmacy_patient_id:patientMode==='chart'?Number(d.pharmacy_patient_id):undefined,controlled:d.controlled==='on',compounded:d.compounded==='on',location_id:Number(d.location_id),refills_authorized:Number(d.refills_authorized)}).unwrap();router.push(`/dashboard/pharmacy/${result.data.id}`)}catch(e){setError(errorMessage(e))}}}>
 <label className="grid gap-1 text-sm">Accident case<select className="h-10 border rounded px-3 bg-background" required value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">Select case</option>{data?.data.map(c=><option key={c.id} value={c.id}>{c.case_number} — {c.title}{!c.accident_date?' (accident date missing)':''}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Patient record type<select className="h-10 border rounded px-3 bg-background" value={patientMode} onChange={e=>setPatientMode(e.target.value)}><option value="chart">Pharmacy patient record</option><option value="legacy">Existing case-linked portal patient</option></select></label>
 {patientMode==='legacy'?<label className="grid gap-1 text-sm">Linked patient<select key={caseId} name="patient_id" required className="h-10 border rounded px-3 bg-background"><option value="">Select patient</option>{selected?.patients.map(p=><option value={p.id} key={p.id}>{p.first_name} {p.last_name}</option>)}</select></label>:<div className="grid gap-2"><label>Find patient by record number or last name<input className="border rounded p-2 w-full bg-background" value={patientSearch} onChange={e=>setPatientSearch(e.target.value)}/></label><label>Pharmacy patient<select key={locationId+patientSearch} name="pharmacy_patient_id" required className="border rounded p-2 w-full bg-background"><option value="">Select location, then patient</option>{charts?.data.data.map(p=><option key={p.id} value={p.id}>{p.record_number} · {p.first_name} {p.last_name} · DOB {p.date_of_birth}</option>)}</select></label><Link className="underline" href="/dashboard/pharmacy/patients">Register a patient without a portal account</Link></div>}
 <label className="grid gap-1 text-sm">Dispensing pharmacy location<select name="location_id" value={locationId} onChange={e=>setLocationId(e.target.value)} className="h-10 border rounded px-3 bg-background" required><option value="">Select location</option>{locations?.data.filter(l=>l.active).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><Choice name="quantity_unit" label="Quantity unit" options={["tablet","capsule","mL","g","each"]}/><Field name="rx_number" label="Pharmacy prescription number"/><Field name="source_reference" label="Source prescription reference"/>
 <Field name="prescriber_name" label="Prescriber name"/><Field name="prescriber_identifier" label="Prescriber identifier (for verification)"/>
 <Field name="medication" label="Medication name"/><Field name="strength" label="Strength"/>
 <Field name="dosage_form" label="Dosage form"/><Field name="directions" label="Directions as prescribed"/>
 <Field name="quantity" label="Prescribed quantity per fill" type="number" min="0.001" step="0.001"/><Field name="refills_authorized" label="Authorized refills (excluding first fill)" type="number" min="0" max="99" defaultValue="0"/>
 <Field name="written_on" label="Prescription date" type="date"/><Field name="expires_on" label="Verified prescription expiration" type="date"/>
 <label className="flex items-center gap-2"><input name="controlled" type="checkbox"/>Controlled substance</label><label className="flex items-center gap-2"><input name="compounded" type="checkbox" checked={compounded} onChange={e=>setCompounded(e.target.checked)}/>Compounded preparation</label>{compounded&&<label className="grid gap-1 text-sm">Compounding preparation type<select name="compound_type" required defaultValue="" className="h-10 border rounded px-3 bg-background"><option value="">Select verified preparation type</option><option value="nonsterile">Nonsterile</option><option value="sterile">Sterile</option></select></label>}<p className="text-sm md:col-span-2">Controlled and compounded prescriptions can be recorded for intake, but cannot be approved or dispensed until their dedicated workflows are validated.</p>
 <div className="md:col-span-2 space-y-3">{error&&<p role="alert" className="text-destructive">{error}</p>}<Button disabled={isLoading||!selected?.accident_date}>{isLoading?'Saving…':'Save prescription for review'}</Button></div>
 </form></div>
}
