"use client"
import Link from 'next/link'
import {useParams} from 'next/navigation'
import {useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {useGetStockTransferQuery,useGetStockTransferDestinationsQuery,usePharmacyStockActionMutation} from '@/store/api/pharmacyApiSlice'
import {TransferCorrections} from '@/components/pharmacy/TransferCorrections'
import {Field,Choice,errorMessage} from '@/components/pharmacy/fields'
import {Button} from '@/components/ui/button'
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card'
export default function Transfer(){
 const id=Number(useParams().id);const {user}=useAuth();const role=user?.role||'';const allowed=['pharmacist','pharmacy_technician'].includes(role);const [correctionPage,setCorrectionPage]=useState(1);const [eventPage,setEventPage]=useState(1);const [key,setKey]=useState(()=>crypto.randomUUID());const [error,setError]=useState('');const [success,setSuccess]=useState('')
 const {currentData,isFetching,isError,refetch}=useGetStockTransferQuery({id,correction_page:correctionPage,event_page:eventPage},{skip:!allowed||!Number.isInteger(id)||id<1});const {data:sites}=useGetStockTransferDestinationsQuery(undefined,{skip:!allowed});const [mutate,{isLoading}]=usePharmacyStockActionMutation();const t=currentData?.data;const name=(id:number)=>sites?.data.find(l=>l.id===id)?.name||`Location #${id}`
 async function save(body:Record<string,unknown>,path='actions'){setError('');setSuccess('');try{await mutate({path:`stock-transfers/${id}/${path}`,body:{...body,version:t?.version,request_id:key}}).unwrap();setSuccess('Custody action recorded.');setKey(crypto.randomUUID())}catch(e){setError(errorMessage(e))}}
 if(!allowed)return <p>Pharmacy staff access is required.</p>
 return <div className="space-y-5 min-w-0"><Link className="underline" href="/dashboard/pharmacy/transfers">Back to stock transfers</Link><h1 className="text-3xl font-bold text-primary">Transfer #{id}</h1><p className="text-sm">Synthetic preview. This records internal custody only. Operational transfer authorization, transport and regulatory reporting are not connected.</p>{error&&<p role="alert" className="text-destructive">{error}</p>}{success&&<p role="status">{success}</p>}{isError?<p role="alert">Could not load this transfer. <Button variant="outline" onClick={()=>refetch()}>Retry</Button></p>:isFetching&&!t?<p role="status">Loading transfer…</p>:t&&<>
 <Card><CardHeader><CardTitle>{t.product.medication}</CardTitle></CardHeader><CardContent className="space-y-2 break-words"><p>{name(t.source_location_id)} → {name(t.destination_location_id)}</p><p>NDC {t.product.ndc} · Lot {t.product.lot_number} · Expires {t.product.expires_on}</p><p>{t.quantity} {t.product.quantity_unit} · Status: {t.status.replaceAll('_',' ')}</p><p>Purpose / reference: {t.reference}</p>{t.can_dispatch&&<p><Link className="underline" href={`/dashboard/pharmacy/stock/${t.source_lot_id}`}>Source receipt #{t.source_lot_id}</Link></p>}{t.destination_lot_id&&<p>Originally recorded receipt {t.received_quantity} {t.product.quantity_unit} · {t.can_receive?<Link className="underline" href={`/dashboard/pharmacy/stock/${t.destination_lot_id}`}>Destination receipt #{t.destination_lot_id}</Link>:`Destination receipt #${t.destination_lot_id}`}</p>}{t.corrected_received_quantity!==null&&<p>Approved corrected receipt: {t.corrected_received_quantity} {t.product.quantity_unit}. Original arrival entry remains retained.</p>}{t.status==='received_discrepancy'&&<p role="alert" className="text-destructive">Receipt differs from dispatched quantity. Stock remains held. A count adjustment cannot clear this custody discrepancy; Use receipt-entry correction only with verified matching physical stock. Actual loss or excess remains an open investigation.</p>}{['received','received_corrected'].includes(t.status)&&<p>Receipt recorded in quarantine. Review the destination receipt before release; source recalls remain enforced.</p>}</CardContent></Card>
 {role==='pharmacist'&&t.status==='planned'&&t.can_dispatch&&<Card><CardHeader><CardTitle>Source custody action</CardTitle></CardHeader><CardContent><form key={key} className="grid gap-3" onSubmit={e=>{e.preventDefault();save(Object.fromEntries(new FormData(e.currentTarget)))}}><p>Dispatch removes the reserved quantity from source stock. Cancel releases the reservation without moving stock. A dispatched transfer cannot be cancelled.</p><Choice name="action" label="Custody action" options={['dispatch','cancel']}/><Field name="evidence" label="Dispatch / cancellation evidence" maxLength={5000}/><label className="flex items-start gap-2 text-sm"><input type="checkbox" required/>I have verified the product, quantity, destination and selected custody action.</label><Button disabled={isLoading||isFetching}>Record source action</Button></form></CardContent></Card>}
 {role==='pharmacist'&&t.status==='dispatched'&&t.can_receive&&(Number(user?.id)===Number(t.dispatched_by)?<p>A different pharmacist assigned to the receiving location must verify receipt.</p>:<Card><CardHeader><CardTitle>Verify actual receipt</CardTitle></CardHeader><CardContent><form key={key} className="grid gap-3" onSubmit={e=>{e.preventDefault();save({...Object.fromEntries(new FormData(e.currentTarget)),action:'receive'})}}><p>Enter the quantity physically verified, including zero if none arrived. A shortage or excess creates a retained discrepancy. Every received lot begins in quarantine.</p><Field name="received_quantity" label={`Actual quantity received (${t.product.quantity_unit})`} type="number" min="0" max="999999.999" step="0.001"/><Field name="evidence" label="Receipt, identity, condition and discrepancy evidence" maxLength={5000}/><label className="flex items-start gap-2 text-sm"><input type="checkbox" required/>I independently checked this receipt and recorded the actual quantity.</label><Button disabled={isLoading||isFetching}>Record verified receipt</Button></form></CardContent></Card>)}
 <TransferCorrections transfer={t} userId={Number(user?.id)} role={role} disabled={isLoading||isFetching} page={correctionPage} changePage={setCorrectionPage} save={(path,body)=>save(body,path)}/>
 <Card><CardHeader><CardTitle>Custody history</CardTitle></CardHeader><CardContent className="space-y-3">{t.events.data.map(e=><div key={e.id} className="border rounded p-3 break-words"><p>{e.action.replaceAll('_',' ')} · Staff #{e.actor_id} · {e.created_at}</p><details><summary className="underline cursor-pointer">Recorded evidence</summary><pre className="whitespace-pre-wrap break-words text-xs mt-2">{e.details}</pre></details></div>)}<div className="flex flex-wrap gap-3 items-center"><Button variant="outline" disabled={isFetching||eventPage===1} onClick={()=>setEventPage(eventPage-1)}>Previous custody events</Button><span>Page {eventPage} of {t.events.last_page}</span><Button variant="outline" disabled={isFetching||eventPage>=t.events.last_page} onClick={()=>setEventPage(eventPage+1)}>Next custody events</Button></div></CardContent></Card></>}</div>
}
