"use client"
import Link from 'next/link'
import {useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {useGetPharmacyPatientsQuery,useGetPharmacyLocationsQuery,usePharmacyStockActionMutation} from '@/store/api/pharmacyApiSlice'
import {Field,errorMessage} from '@/components/pharmacy/fields'
import {Button} from '@/components/ui/button'
export default function PharmacyPatients(){
 const {user}=useAuth();const allowed=['pharmacist','pharmacy_technician'].includes(user?.role||'');const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [key,setKey]=useState(()=>crypto.randomUUID());const [error,setError]=useState('');const {currentData,isFetching,isError}=useGetPharmacyPatientsQuery({search,page},{skip:!allowed});const {data:locations}=useGetPharmacyLocationsQuery(undefined,{skip:!allowed});const [save,{isLoading}]=usePharmacyStockActionMutation();const d=currentData?.data
 if(!allowed)return <p>Clinical patient records are restricted to pharmacy staff.</p>
 return <div className="space-y-5"><Link className="underline" href="/dashboard/pharmacy">Back to pharmacy</Link><h1 className="text-3xl font-bold text-primary">Pharmacy patient records</h1><p>Synthetic preview. Patients do not need portal accounts. Check identity before creating a record; records are never merged by email.</p><label>Find by record number or last name<input className="border rounded p-2 ml-3 bg-background" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label>{isError?<p role="alert">Could not load patient records.</p>:isFetching?<p role="status">Loading patients…</p>:<><ul className="space-y-3">{d?.data.map(p=><li key={p.id}><Link className="underline" href={`/dashboard/pharmacy/patients/${p.id}`}>{p.record_number} · {p.first_name} {p.last_name}</Link> · DOB {p.date_of_birth}</li>)}</ul>{!d?.data.length&&<p>No patient records found in your assigned locations.</p>}<div className="flex gap-4"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page} of {d?.last_page||1}</span><Button variant="outline" disabled={page>=(d?.last_page||1)} onClick={()=>setPage(page+1)}>Next</Button></div></>}
 <details><summary className="cursor-pointer font-semibold">Register a patient</summary><form className="grid gap-4 md:grid-cols-2 mt-4 max-w-4xl" onSubmit={async e=>{e.preventDefault();setError('');const form=e.currentTarget;const f=Object.fromEntries(new FormData(form));try{await save({path:'patients',body:{...f,request_id:key,location_id:Number(f.location_id)}}).unwrap();setKey(crypto.randomUUID());form.reset()}catch(e){setError(errorMessage(e))}}}>
 <label>Pharmacy location<select className="border rounded p-2 w-full bg-background" required name="location_id"><option value="">Select assigned location</option>{locations?.data.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><Field name="record_number" label="Unique patient record number"/><Field name="first_name" label="First name"/><Field name="last_name" label="Last name"/><Field name="date_of_birth" label="Date of birth" type="date"/><Field name="phone" label="Phone" required={false}/><Field name="address" label="Address" required={false}/><Field name="identity_reference" label="Identity verification reference"/>{error&&<p role="alert">{error}</p>}<Button disabled={isLoading}>Create patient record</Button></form></details></div>
}
