"use client"
import Link from 'next/link'
import {useState} from 'react'
import {useParams} from 'next/navigation'
import {useAuth} from '@/hooks/useAuth'
import {useGetRecallNoticeQuery,useGetPharmacyLocationsQuery} from '@/store/api/pharmacyApiSlice'
import {Button} from '@/components/ui/button'
export default function Recall(){
 const id=Number(useParams().id);const {user}=useAuth();const allowed=['pharmacist','pharmacy_technician'].includes(user?.role||'');const [stockPage,setStockPage]=useState(1);const [fillPage,setFillPage]=useState(1)
 const {currentData,isFetching,isError,refetch}=useGetRecallNoticeQuery({id,stock_page:stockPage,fill_page:fillPage},{skip:!allowed||!Number.isInteger(id)||id<1});const {data:sites}=useGetPharmacyLocationsQuery(undefined,{skip:!allowed});const n=currentData?.data;const name=(id:number)=>sites?.data.find(x=>x.id===id)?.name||`Location #${id}`
 if(!allowed)return <p>Pharmacy staff access is required.</p>
 return <div className="space-y-5 min-w-0"><Link className="underline" href="/dashboard/pharmacy/recalls">Back to recall register</Link><h1 className="text-3xl font-bold text-primary">Recall notice #{id}</h1>{isError?<p role="alert">This notice could not be loaded. <Button variant="outline" onClick={()=>refetch()}>Retry</Button></p>:isFetching?<p role="status">Loading recall trace…</p>:n&&<>
 <section className="border rounded p-4 space-y-2 break-words"><h2 className="font-semibold text-xl">{n.product_description}</h2><p>{n.reference}</p><p>NDC: {n.ndcs.join(', ')} · {n.all_lots?'All lots':`Lot ${n.lot_number}`}</p><p>Recorded by staff #{n.created_by} · {n.created_at}</p><p className="whitespace-pre-wrap">{n.evidence}</p><p className="font-semibold text-red-700 dark:text-red-300">Matching stock is held across the organization. A normal stock release or count cannot clear this notice.</p></section>
 <p>These lists cover your currently assigned locations only. They include historical records; retained quantities and original stock status are unchanged by notice registration. An available status does not override this hold. Staff must review outstanding reservations and prior handovers; no patient communication has been sent.</p>
 <section className="space-y-3"><h2 className="text-xl font-semibold">Affected stock receipts</h2>{n.stock.data.map(l=><div key={l.id} className="border rounded p-4 space-y-1 break-words"><Link className="underline" href={`/dashboard/pharmacy/stock/${l.id}`}>Receipt #{l.id} · {l.medication}</Link><p>{name(l.location_id)} · Lot {l.lot_number} · NDC {l.ndc}</p><p>On hand {l.on_hand} · Reserved {l.reserved} {l.quantity_unit} · Recorded status {l.status}</p><p className="text-red-700 dark:text-red-300">Organization recall hold</p></div>)}{!n.stock.data.length&&<p>No matching receipts at your assigned locations.</p>}<Pager page={stockPage} pages={n.stock.last_page} total={n.stock.total} label="receipts" change={setStockPage}/></section>
 <section className="space-y-3"><h2 className="text-xl font-semibold">Affected fill history</h2>{n.fills.data.map(f=><div key={f.id} className="border rounded p-4 space-y-1 break-words"><Link className="underline" href={`/dashboard/pharmacy/${f.prescription_id}#fill-${f.id}`}>{f.rx_number} · Fill {f.fill_number}</Link><p>{name(f.location_id)} · Receipt #{f.stock_lot_id} · {f.quantity} {f.quantity_unit} · {f.fulfillment_status}</p><p>{f.created_at}</p></div>)}{!n.fills.data.length&&<p>No matching fills at your assigned locations.</p>}<Pager page={fillPage} pages={n.fills.last_page} total={n.fills.total} label="fills" change={setFillPage}/></section></>}</div>
}
function Pager({page,pages,total,label,change}:{page:number;pages:number;total:number;label:string;change:(p:number)=>void}){return <div className="flex flex-wrap gap-3 items-center"><Button variant="outline" disabled={page===1} onClick={()=>change(page-1)}>Previous {label}</Button><span>Page {page} of {pages} · {total} {label}</span><Button variant="outline" disabled={page>=pages} onClick={()=>change(page+1)}>Next {label}</Button></div>}
