"use client"
import {FormEvent,useRef,useState} from 'react'
import {Button} from '@/components/ui/button'
import {useAuth} from '@/hooks/useAuth'
import {Field,errorMessage} from './fields'
import {CompoundBatch,BeyondUseContext,useGetBeyondUseHistoryQuery,useGetBeyondUseContextQuery,useGetBeyondUseProposalQuery,useCreateBeyondUseProposalMutation,useDecideBeyondUseProposalMutation} from '@/store/api/pharmacyApiSlice'
function Text({name,label}:{name:string;label:string}){return <label className="grid gap-1 text-sm">{label}<textarea name={name} required maxLength={5000} rows={3} className="border rounded p-2 bg-background"/></label>}
export function BeyondUse({batch}:{batch:CompoundBatch}){
 const {user}=useAuth();const id=batch.execution?.id??0;const [page,setPage]=useState(1);const [selected,setSelected]=useState<number|null>(null);const [creating,setCreating]=useState(false)
 const q=useGetBeyondUseHistoryQuery({id,page},{skip:!id});const latest=useGetBeyondUseHistoryQuery({id,page:1},{skip:!id})
 if(!id)return null
 if(q.isError||latest.isError)return <p role="alert">Could not load dating proposals. <Button onClick={()=>{q.refetch();latest.refetch()}}>Retry dating history</Button></p>
 if(!q.currentData||!latest.currentData)return <p>Loading dating proposals…</p>
 const last=latest.currentData.data.data[0];const busy=q.isFetching||latest.isFetching
 return <section className="border-t pt-4 space-y-4"><h3 className="text-lg font-semibold">Beyond-use dating proposals</h3><p className="text-sm">Retain a pharmacist-supplied date, limiting evidence, storage and packaging. Documentary review does not validate clinical limits or release medication.</p>{q.currentData.data.data.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-2 border-b pb-2"><p>Dating proposal {p.id} · {p.status}</p><Button variant="outline" disabled={busy} onClick={()=>{setSelected(p.id);setCreating(false)}}>Open dating proposal {p.id}</Button></div>)}{!q.currentData.data.total&&<p>No retained dating proposals.</p>}<div className="flex gap-3 items-center"><Button variant="outline" disabled={busy||page===1} onClick={()=>setPage(page-1)}>Previous dating proposals</Button><span>Page {page} / {q.currentData.data.last_page}</span><Button variant="outline" disabled={busy||page>=q.currentData.data.last_page} onClick={()=>setPage(page+1)}>Next dating proposals</Button></div>
 {user?.role==='pharmacist'&&(last?.status==='pending'?<p>Review or reject the pending dating proposal before retaining a replacement.</p>:<Button disabled={busy} variant="outline" onClick={()=>{setCreating(!creating);setSelected(null)}}>{creating?'Close dating form':'Propose beyond-use date'}</Button>)}
 {creating&&<fieldset disabled={busy} className="min-w-0"><Context execution={id} previous={last?.id??null} onDone={value=>{setCreating(false);setSelected(value);setPage(1)}}/></fieldset>}{selected&&<Detail key={selected} id={selected} batch={batch}/>}</section>
}
function Context({execution,previous,onDone}:{execution:number;previous:number|null;onDone:(id:number)=>void}){
 const q=useGetBeyondUseContextQuery(execution)
 if(q.isError)return <p role="alert">Dating prerequisites are unavailable. {errorMessage(q.error)} <Button onClick={()=>q.refetch()}>Retry dating prerequisites</Button></p>
 if(!q.currentData)return <p>Checking reviewed quality evidence…</p>
 return <fieldset disabled={q.isFetching} className="min-w-0"><Create context={q.currentData.data} previous={previous} onDone={onDone}/></fieldset>
}
function Create({context,previous,onDone}:{context:BeyondUseContext;previous:number|null;onDone:(id:number)=>void}){
 const initial=useRef({context,previous}).current;const request=useRef<{payload:string;id:string}|null>(null);const [rows,setRows]=useState([1]);const next=useRef(2)
 const [save,{isLoading}]=useCreateBeyondUseProposalMutation();const [error,setError]=useState('');const source=initial.context
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const v=(key:string)=>String(f.get(key)??'')
 const body={id:source.execution_id,previous_id:initial.previous,source_hash:source.source_hash,proposal:{prepared_at:v('prepared_at'),proposed_bud_at:v('proposed_bud_at'),timezone:v('timezone'),preparation_time_reference:v('preparation_time_reference'),container_reference:v('container_reference'),storage_conditions:v('storage_conditions'),basis_reference:v('basis_reference'),rationale:v('rationale'),limits:rows.map(id=>({key:v(`key_${id}`),not_after:v(`limit_${id}`),reference:v(`reference_${id}`)}))}}
 const payload=JSON.stringify(body);if(request.current?.payload!==payload)request.current={payload,id:crypto.randomUUID()}
 try{const r=await save({...body,request_id:request.current.id}).unwrap();onDone(r.data.id)}catch(e){setError(errorMessage(e))}}
 const changed=context.source_hash!==source.source_hash
 return <form onSubmit={submit} className="rounded border p-4 space-y-3"><h4 className="font-semibold">New dating proposal</h4><p>Recorded preparation date: {source.prepared_on}. Quality record: {source.quality_record_id}.</p><p className="text-sm">Enter timestamps with seconds and their UTC offset, for example 2026-10-04T09:00:00-04:00. Enter the IANA timezone separately, for example America/Detroit. No date or duration is calculated for you.</p>{changed&&<p role="alert">Quality evidence changed. Preserve your notes, then close and reopen the form to compare current records.</p>}<fieldset disabled={isLoading||changed} className="min-w-0 space-y-3"><Field name="prepared_at" label="Exact preparation timestamp with offset"/><Field name="proposed_bud_at" label="Proposed beyond-use timestamp with offset"/><Field name="timezone" label="Preparation and dating timezone"/><Text name="preparation_time_reference" label="Preparation time source evidence"/><Text name="container_reference" label="Packaging and container evidence"/><Text name="storage_conditions" label="Required storage conditions"/><Text name="basis_reference" label="Dating basis and standard references"/><Text name="rationale" label="Dating rationale"/>{rows.map((id,i)=><fieldset key={id} className="border rounded p-3 space-y-2"><legend>Limiting factor {i+1}</legend><Field name={`key_${id}`} label={`Limit ${i+1} identifier`} maxLength={40}/><Field name={`limit_${id}`} label={`Limit ${i+1} timestamp with offset`}/><Text name={`reference_${id}`} label={`Limit ${i+1} supporting reference`}/>{rows.length>1&&<Button type="button" variant="outline" onClick={()=>setRows(rows.filter(r=>r!==id))}>Remove limiting factor {i+1}</Button>}</fieldset>)}<Button type="button" variant="outline" disabled={rows.length>=100} onClick={()=>setRows([...rows,next.current++])}>Add limiting factor</Button>{error&&<p role="alert">{error}</p>}<Button>Retain dating proposal</Button></fieldset></form>
}
function Detail({id,batch}:{id:number;batch:CompoundBatch}){
 const {user}=useAuth();const q=useGetBeyondUseProposalQuery(id);const [save,{isLoading}]=useDecideBeyondUseProposalMutation();const [error,setError]=useState('');const [success,setSuccess]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setSuccess('');const f=new FormData(e.currentTarget);try{await save({id,decision:String(f.get('decision')) as 'reviewed'|'rejected',evidence:String(f.get('evidence'))}).unwrap();setSuccess('Dating decision retained. No medication release authorized.')}catch(e){setError(errorMessage(e))}}
 if(q.isError)return <p role="alert">Could not load dating evidence. <Button onClick={()=>q.refetch()}>Retry dating detail</Button></p>
 if(!q.currentData)return <p>Loading dating evidence…</p>
 const p=q.currentData.data;const v=p.proposal.evidence;const independent=Number(user?.id)!==p.created_by&&Number(user?.id)!==batch.execution?.created_by&&!batch.execution?.addenda.some(a=>a.created_by===Number(user?.id))
 return <article className="border rounded p-4 space-y-3"><h4 className="font-semibold">Dating proposal {p.id} · {p.status}</h4><p>Quality record {p.quality_record_id} · Recorded by user {p.created_by} · {p.created_at}</p>{p.elapsed&&<p role="alert">The proposed beyond-use timestamp has elapsed. This record cannot receive a new review.</p>}<dl className="space-y-2">{Object.entries(v).filter(([key])=>key!=='limits').map(([key,value])=><div key={key}><dt className="font-medium capitalize">{key.replaceAll('_',' ')}</dt><dd className="whitespace-pre-wrap break-words">{String(value)}</dd></div>)}</dl>{v.limits.map(l=><div key={l.key} className="border-b pb-2"><strong>{l.key} · {l.not_after}</strong><p className="whitespace-pre-wrap break-words">{l.reference}</p></div>)}<p>Proposed date in UTC: {p.proposal.proposed_bud_at_utc}</p><p>Earliest supplied limit in UTC: {p.proposal.earliest_supplied_limit_utc}</p>{p.reviewed_by&&<><p>Reviewed by user {p.reviewed_by} · {p.reviewed_at}</p><p className="whitespace-pre-wrap break-words">{p.review_evidence}</p></>}
 {p.status==='pending'&&user?.role==='pharmacist'&&(independent?<form onSubmit={submit}><fieldset disabled={isLoading||q.isFetching} className="space-y-3"><label className="grid gap-1 text-sm">Dating proposal decision<select name="decision" defaultValue="rejected" className="border rounded p-2 bg-background"><option value="rejected">Reject proposal for replacement</option>{!p.elapsed&&<option value="reviewed">Record independent documentary review</option>}</select></label><Text name="evidence" label="Dating review findings and evidence"/>{error&&<p role="alert">{error}</p>}<Button>Save dating decision</Button></fieldset></form>:<p>Another pharmacist independent of dating and preparation must review this proposal.</p>)}{success&&<p role="status">{success}</p>}</article>
}
