'use client'
import {FormEvent,useRef,useState} from 'react'
import {Button} from '@/components/ui/button'
import {Field,errorMessage} from './fields'
import {ContainerLabelPrint,ContainerLabelSummary,useGetContainerLabelComparisonsQuery,useCreateContainerLabelComparisonMutation} from '@/store/api/pharmacyApiSlice'
export function ContainerLabelComparisons({proof,print,disabled,onClose}:{proof:ContainerLabelSummary;print:ContainerLabelPrint|null;disabled:boolean;onClose:()=>void}){
 const [page,setPage]=useState(1);const q=useGetContainerLabelComparisonsQuery({id:proof.id,page})
 return <section className="space-y-3 border-t pt-3"><h5 className="font-semibold">Container code comparisons</h5><p>Each comparison identifies a retained print record. It does not validate a physical scanner or authorize medication release.</p>{!proof.barcode_code&&<p>This historical proof has no internal barcode. Retain a new proof and output evidence before recording a code comparison.</p>}
 {q.isError?<p role="alert">Comparison history unavailable. <Button onClick={()=>q.refetch()}>Retry code comparison history</Button></p>:!q.currentData?<p>Loading code comparisons…</p>:<>{q.currentData.data.data.map(c=><article key={c.id} className="border rounded p-3 space-y-1"><p>Comparison {c.id} · Output record {c.print_id} · {c.input_method==='manual'?'Manual comparison':'Scanner-reported input'} · Staff {c.created_by}</p><p>{c.container_identifier} · {c.barcode_code}</p>{c.manual_reason&&<p>Manual reason: {c.manual_reason}</p>}<p>Evidence: {c.evidence}</p><p>Recorded {c.created_at}</p></article>)}{!q.currentData.data.total&&<p>No code comparisons retained.</p>}<div className="flex flex-wrap gap-2 items-center"><Button disabled={page===1||q.isFetching} onClick={()=>setPage(page-1)}>Previous code comparisons</Button><span>Page {page} / {q.currentData.data.last_page}</span><Button disabled={page>=q.currentData.data.last_page||q.isFetching} onClick={()=>setPage(page+1)}>Next code comparisons</Button></div></>}
 {print&&proof.barcode_code&&<fieldset disabled={disabled||q.isFetching||q.isError||!q.currentData}><Compare key={`${proof.id}-${print.id}`} proof={proof} print={print} onClose={onClose} onDone={()=>{setPage(1);onClose()}}/></fieldset>}</section>
}
function Compare({proof,print,onClose,onDone}:{proof:ContainerLabelSummary;print:ContainerLabelPrint;onClose:()=>void;onDone:()=>void}){
 const [method,setMethod]=useState<''|'manual'|'scanner'>('');const [save,{isLoading}]=useCreateContainerLabelComparisonMutation();const [error,setError]=useState('');const request=useRef<{body:string;id:string}|null>(null)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!method)return;setError('');const f=new FormData(e.currentTarget);const body={id:proof.id,print_id:print.id,document_hash:print.document_hash,label_code:String(f.get('label_code')),container_identifier:String(f.get('container_identifier')),input_method:method,manual_reason:method==='manual'?String(f.get('manual_reason')):null,evidence:String(f.get('evidence')),confirmed:f.get('confirmed')==='on'};const serialized=JSON.stringify(body);if(request.current?.body!==serialized)request.current={body:serialized,id:crypto.randomUUID()};try{await save({...body,request_id:request.current.id}).unwrap();onDone()}catch(err){setError(errorMessage(err))}}
 return <form onSubmit={submit} className="border rounded p-3 space-y-3"><h5 className="font-semibold">Compare output record {print.id}</h5><p>{print.copies} simulated copies · {print.occurred_on} · {print.reason}</p><p>Read the code and container identifier from the synthetic output being compared. Neither field is filled automatically.</p><fieldset disabled={isLoading} className="grid gap-3"><label className="grid gap-1">Code input method<select value={method} required onChange={e=>setMethod(e.target.value as typeof method)} className="border rounded p-2 bg-background"><option value="" disabled>Select how the code was entered</option><option value="manual">Manual comparison</option><option value="scanner">Scanner-reported input</option></select></label><Field name="label_code" label="Observed internal label code" maxLength={32}/><Field name="container_identifier" label="Observed container identifier" maxLength={64}/>{method==='manual'&&<Field name="manual_reason" label="Manual comparison reason" maxLength={2000}/>}<label className="grid gap-1">Container comparison evidence<textarea name="evidence" required rows={3} maxLength={5000} className="border rounded p-2 bg-background"/></label><label className="flex items-start gap-2"><input name="confirmed" type="checkbox" required/>I compared this exact synthetic output and recorded the input method accurately. No physical device acceptance or release is certified.</label>{error&&<p role="alert">{error}</p>}<div className="flex flex-wrap gap-2"><Button>{isLoading?'Saving comparison…':'Retain container code comparison'}</Button><Button type="button" variant="outline" onClick={onClose}>Cancel code comparison</Button></div></fieldset></form>
}
