'use client'
import {FormEvent,useEffect,useState} from 'react'
import {useSelector} from 'react-redux'
import {RootState} from '@/store/store'
import {useAuth} from '@/hooks/useAuth'
import {ContainerLabelPrints} from './container-label-prints'
import {Button} from '@/components/ui/button'
import {errorMessage} from './fields'
import {CompoundBatch,ContainerLabelContext,useGetSuitabilityContextQuery,useGetContainerLabelContextQuery,useGetContainerLabelsQuery,useCreateContainerLabelMutation} from '@/store/api/pharmacyApiSlice'
export function ContainerLabels({batch}:{batch:CompoundBatch}){
 const {user}=useAuth();const id=batch.execution?.id??0;const [page,setPage]=useState(1);const [identifier,setIdentifier]=useState('');const [selected,setSelected]=useState<number|null>(null)
 const q=useGetContainerLabelsQuery({id,page},{skip:!id});const containers=useGetSuitabilityContextQuery(id,{skip:!id||user?.role!=='pharmacist'})
 if(!id)return null
 return <section className="border-t pt-4 space-y-4"><h3 className="text-lg font-semibold">Finished-container label proofs</h3><p>Synthetic proofs only. Saving or viewing a proof does not print it or authorize dispensing.</p>
 {q.isError?<p role="alert">Label history unavailable. <Button onClick={()=>q.refetch()}>Retry container labels</Button></p>:!q.currentData?<p>Loading label history…</p>:<><ul className="space-y-3">{q.currentData.data.data.map(p=><li key={p.id} className="border rounded p-3 space-y-2"><p>{p.container_identifier} · Revision {p.revision} · Author {p.created_by} · {p.created_at}</p><p className="break-all">{p.barcode_code?`Internal proof code: ${p.barcode_code}`:"Historical proof without an internal barcode; retain a new proof before barcode checks."}</p><p className="break-all text-sm">SHA-256: {p.document_hash}</p>{user?.role==='pharmacist'&&<Button variant="outline" disabled={q.isFetching} onClick={()=>setSelected(selected===p.id?null:p.id)}>{selected===p.id?'Close proof':`Open container proof ${p.id}`}</Button>}{selected===p.id&&<Document id={p.id}/>}<ContainerLabelPrints proof={p} disabled={q.isFetching}/></li>)}</ul>{!q.currentData.data.total&&<p>No container label proofs retained.</p>}<div className="flex flex-wrap gap-3 items-center"><Button disabled={q.isFetching||page===1} onClick={()=>setPage(page-1)}>Previous container labels</Button><span>Page {page} / {q.currentData.data.last_page}</span><Button disabled={q.isFetching||page>=q.currentData.data.last_page} onClick={()=>setPage(page+1)}>Next container labels</Button></div></>}
 {user?.role==='pharmacist'&&(containers.isError?<p role="alert">Current container evidence unavailable. {errorMessage(containers.error)} <Button onClick={()=>containers.refetch()}>Retry label container evidence</Button></p>:containers.currentData?<><label className="grid gap-1">Container for a new label proof<select value={identifier} disabled={containers.isFetching||q.isFetching||q.isError} onChange={e=>setIdentifier(e.target.value)} className="border rounded p-2 bg-background"><option value="">Select a nonempty container</option>{containers.currentData.data.containers.map(c=><option key={c.identifier} value={c.identifier}>{c.identifier} · {c.quantity} {containers.currentData?.data.unit}</option>)}</select></label>{identifier&&<Source key={identifier} execution={id} identifier={identifier} onDone={proof=>{setIdentifier('');setSelected(proof);setPage(1)}}/>}</>:<p>Loading current containers…</p>)}
 </section>
}
function Source({execution,identifier,onDone}:{execution:number;identifier:string;onDone:(id:number)=>void}){
 const q=useGetContainerLabelContextQuery({id:execution,identifier})
 if(q.isError)return <p role="alert">This container is not eligible for a new proof. {errorMessage(q.error)} <Button onClick={()=>q.refetch()}>Recheck label prerequisites</Button></p>
 if(!q.currentData)return <p>Checking patient, container and reviewed evidence…</p>
 return <fieldset disabled={q.isFetching}><Create execution={execution} context={q.currentData.data} onDone={onDone}/></fieldset>
}
function Create({execution,context,onDone}:{execution:number;context:ContainerLabelContext;onDone:(id:number)=>void}){
 const [source]=useState(context);const [request]=useState(()=>crypto.randomUUID());const [save,{isLoading}]=useCreateContainerLabelMutation();const [error,setError]=useState('');const stale=source.source_hash!==context.source_hash||source.previous_id!==context.previous_id
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(stale)return;setError('');try{const r=await save({id:execution,identifier:source.container.identifier,previous_id:source.previous_id,source_hash:source.source_hash,request_id:request}).unwrap();onDone(r.data.id)}catch(err){setError(errorMessage(err))}}
 const rx=source.prescription;const d=source.dating_evidence
 return <form onSubmit={submit} className="border rounded p-4 space-y-3"><h4 className="font-semibold">Review source for container proof</h4><p>{source.patient.first_name} {source.patient.last_name} · {source.location.name}</p><p>{source.location.address}</p><p>Rx {rx.rx_number} · {rx.medication} {rx.strength} · {rx.dosage_form}</p><p>Prescriber: {rx.prescriber_name}</p><p>Directions: {rx.directions}</p><p>{source.container.identifier} · {source.container.quantity} {source.unit}</p><p>Prepared: {d.prepared_at} · Proposed beyond-use: {d.proposed_bud_at} ({d.timezone})</p><p>Storage: {d.storage_conditions}</p>{stale&&<p role="alert">Source or latest proof changed. Clear the container selection and select it again to review current evidence.</p>}<fieldset disabled={isLoading||stale} className="space-y-3"><label className="flex items-start gap-2"><input type="checkbox" required/>I compared these synthetic source details. This proof remains quarantined and is not for dispensing.</label>{error&&<p role="alert">{error}</p>}<Button>{isLoading?'Retaining proof…':'Retain container label proof'}</Button></fieldset></form>
}
function Document({id}:{id:number}){
 const token=useSelector((s:RootState)=>s.auth.token?.access_token);const [file,setFile]=useState<{url:string;token:string;id:number}|null>(null);const [error,setError]=useState('')
 useEffect(()=>{setFile(null);setError('');if(!token)return;const controller=new AbortController();let url='';const base=process.env.NEXT_PUBLIC_API_BASE_URL||'http://localhost:8000/api';fetch(`${base.replace(/\/$/,'')}/pharmacy/container-labels/${id}/document`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Proof cannot be opened: access, integrity or current source checks failed. Superseded proofs cannot be used.');return r.blob()}).then(blob=>{if(!controller.signal.aborted){url=URL.createObjectURL(blob);setFile({url,token,id})}}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>{controller.abort();if(url)URL.revokeObjectURL(url)}},[id,token])
 return error?<p role="alert">{error}</p>:file?.token===token&&file?.id===id?<div className="space-y-2"><iframe title={`Synthetic container label ${id}`} sandbox="" src={file.url} className="w-full h-[560px] border bg-white"/><a className="underline" download={`synthetic-container-proof-${id}.html`} href={file.url}>Download synthetic proof</a><p>Downloading does not establish printing or authorize medication release.</p></div>:<p>Checking proof access and integrity…</p>
}
