"use client"
import {FormEvent,useRef,useState} from 'react'
import {Button} from '@/components/ui/button'
import {useAuth} from '@/hooks/useAuth'
import {Field,errorMessage} from './fields'
import {CompoundBatch,ContainerFinding,ContainerCustodyContext,useGetContainerCustodyContextQuery,useGetContainerCustodyHistoryQuery,useGetContainerCustodyProposalQuery,useCreateContainerCustodyProposalMutation,useDecideContainerCustodyProposalMutation} from '@/store/api/pharmacyApiSlice'
function Evidence({name,label}:{name:string;label:string}){return <label className="grid gap-1 text-sm">{label}<textarea name={name} required maxLength={5000} rows={3} className="border rounded p-2 bg-background"/></label>}
export function ContainerCustody({batch}:{batch:CompoundBatch}){
 const {user}=useAuth();const id=batch.execution?.id??0;const [page,setPage]=useState(1);const [selected,setSelected]=useState<number|null>(null);const [creating,setCreating]=useState(false)
 const q=useGetContainerCustodyHistoryQuery({id,page},{skip:!id})
 if(!id)return null
 if(q.isError)return <p role="alert">Could not load container custody. <Button onClick={()=>q.refetch()}>Retry container history</Button></p>
 if(!q.currentData)return <p>Loading container custody…</p>
 return <section id="container-custody" className="border-t pt-4 space-y-4"><h3 className="text-lg font-semibold">Container custody</h3><p className="text-sm">Record each container and the unpackaged remainder separately, including losses or disposal. Historical packaging supports traceability even after expiry or recall. These records do not clear clinical holds or authorize dispensing.</p>{q.currentData.data.data.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-2 border-b pb-2"><p>Container custody {p.id} · {p.status}</p><Button variant="outline" disabled={q.isFetching} onClick={()=>{setSelected(p.id);setCreating(false)}}>Open container custody {p.id}</Button></div>)}{!q.currentData.data.total&&<p>No container custody records.</p>}<div className="flex gap-3 items-center"><Button variant="outline" disabled={q.isFetching||page===1} onClick={()=>setPage(page-1)}>Previous container records</Button><span>Page {page} / {q.currentData.data.last_page}</span><Button variant="outline" disabled={q.isFetching||page>=q.currentData.data.last_page} onClick={()=>setPage(page+1)}>Next container records</Button></div>
 {q.currentData.pending?<p>Resolve the pending output or container custody proposal before recording another.</p>:user?.role==='pharmacist'&&<Button variant="outline" disabled={q.isFetching} onClick={()=>{setCreating(!creating);setSelected(null)}}>{creating?'Close container form':'Record container findings'}</Button>}
 {creating&&!q.currentData.pending&&<fieldset disabled={q.isFetching} className="min-w-0"><Context id={id} onDone={value=>{setCreating(false);setSelected(value);setPage(1)}}/></fieldset>}{selected&&<Detail key={selected} id={selected} batch={batch}/>}</section>
}
function Context({id,onDone}:{id:number;onDone:(id:number)=>void}){
 const q=useGetContainerCustodyContextQuery(id)
 if(q.isError)return <p role="alert">Container evidence is unavailable. {errorMessage(q.error)} <Button onClick={()=>q.refetch()}>Retry container evidence</Button></p>
 if(!q.currentData)return <p>Loading retained packaging and current quantities…</p>
 return <fieldset disabled={q.isFetching} className="min-w-0"><Create context={q.currentData.data} onDone={onDone}/></fieldset>
}
function FindingFields({prefix,label,quantity,unit}:{prefix:string;label:string;quantity:string;unit:string}){
 return <fieldset className="border rounded p-3 space-y-3"><legend>{label}</legend><p>Currently held: {quantity} {unit}</p><Field name={`${prefix}_retained`} label={`${label}: retained in quarantine (${unit})`}/><Field name={`${prefix}_disposed`} label={`${label}: disposed (${unit})`}/><Field name={`${prefix}_missing`} label={`${label}: unaccounted (${unit})`}/><Evidence name={`${prefix}_evidence`} label={`${label}: custody findings and evidence`}/></fieldset>
}
function Create({context,onDone}:{context:ContainerCustodyContext;onDone:(id:number)=>void}){
 const source=useRef(context).current;const request=useRef<{payload:string;id:string}|null>(null);const [save,{isLoading}]=useCreateContainerCustodyProposalMutation();const [error,setError]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const v=(key:string)=>String(f.get(key)??'');const finding=(prefix:string):ContainerFinding=>({retained_quarantined:v(`${prefix}_retained`),disposed_output:v(`${prefix}_disposed`),unaccounted_output:v(`${prefix}_missing`),evidence:v(`${prefix}_evidence`)})
 const body={id:source.execution_id,source_hash:source.source_hash,decision:{unit:source.balance.unit,containers:source.balance.containers.map((c,i)=>({identifier:c.identifier,...finding(`c${i}`)})),unpackaged:finding('unpackaged'),evidence:v('evidence')}}
 const payload=JSON.stringify(body);if(request.current?.payload!==payload)request.current={payload,id:crypto.randomUUID()}
 try{const r=await save({...body,request_id:request.current.id}).unwrap();onDone(r.data.id)}catch(e){setError(errorMessage(e))}}
 const changed=context.source_hash!==source.source_hash
 return <form onSubmit={submit} className="border rounded p-4 space-y-3"><h4 className="font-semibold">New container custody findings</h4><p>Packaging proposal {source.packaging_proposal_id}. Previously disposed: {source.balance.previously_disposed} {source.balance.unit}.</p><p className="text-sm">Enter every quantity explicitly, including zero, with up to three decimal places. Retained, disposed and unaccounted quantities must equal the held amount for each container. Saving preserves findings; independent application is required to change accounted disposal. Unaccounted quantities block application.</p>{changed&&<p role="alert">Source evidence changed. Preserve your notes, then close and reopen this form.</p>}<fieldset disabled={isLoading||changed} className="space-y-3 min-w-0">{source.balance.containers.map((c,i)=><FindingFields key={c.identifier} prefix={`c${i}`} label={`Container ${c.identifier}`} quantity={c.quantity} unit={source.balance.unit}/>)}<FindingFields prefix="unpackaged" label="Unpackaged remainder" quantity={source.balance.unpackaged_quantity} unit={source.balance.unit}/><Evidence name="evidence" label="Overall custody findings and supporting evidence"/>{error&&<p role="alert">{error}</p>}<Button>Retain container findings</Button></fieldset></form>
}
function Finding({label,value,unit}:{label:string;value:ContainerFinding;unit:string}){return <div className="border-b pb-2"><strong>{label}</strong><p>Retained: {value.retained_quarantined} · Disposed: {value.disposed_output} · Unaccounted: {value.unaccounted_output} {unit}</p><p className="whitespace-pre-wrap break-words">{value.evidence}</p></div>}
function Detail({id,batch}:{id:number;batch:CompoundBatch}){
 const {user}=useAuth();const q=useGetContainerCustodyProposalQuery(id);const [save,{isLoading}]=useDecideContainerCustodyProposalMutation();const [error,setError]=useState('');const [success,setSuccess]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setSuccess('');const f=new FormData(e.currentTarget);try{await save({id,decision:String(f.get('decision')) as 'applied'|'rejected',evidence:String(f.get('evidence'))}).unwrap();setSuccess('Container custody decision retained. No medication release authorized.')}catch(e){setError(errorMessage(e))}}
 if(q.isError)return <p role="alert">Could not load container findings. <Button onClick={()=>q.refetch()}>Retry container detail</Button></p>
 if(!q.currentData)return <p>Loading container findings…</p>
 const p=q.currentData.data;const v=p.proposal;const independent=Number(user?.id)!==p.created_by&&Number(user?.id)!==batch.execution?.created_by&&!batch.execution?.addenda.some(a=>a.created_by===Number(user?.id))
 return <article className="border rounded p-4 space-y-3"><h4 className="font-semibold">Container custody {p.id} · {p.status}</h4><p>Packaging proposal {p.packaging_proposal_id} · Recorded by user {p.created_by} · {p.created_at}</p><p>Held before: {v.held_before} {v.unit} · Previously disposed: {v.previously_disposed} {v.unit}</p>{v.containers.map(c=><Finding key={c.identifier} label={`Container ${c.identifier}`} value={c} unit={v.unit}/>)}<Finding label="Unpackaged remainder" value={v.unpackaged} unit={v.unit}/><p className="whitespace-pre-wrap break-words">{v.evidence}</p>{!v.accounting_complete&&<p role="alert">Unaccounted output remains unresolved. This proposal cannot be applied.</p>}{p.reviewed_by&&<><p>Reviewed by user {p.reviewed_by} · {p.reviewed_at}</p><p className="whitespace-pre-wrap break-words">{p.review_evidence}</p></>}
 {p.status==='pending'&&user?.role==='pharmacist'&&(independent?<form onSubmit={submit}><fieldset disabled={isLoading||q.isFetching} className="space-y-3"><label className="grid gap-1 text-sm">Container custody decision<select name="decision" defaultValue="rejected" className="border rounded p-2 bg-background"><option value="rejected">Reject proposal; preserve findings</option>{v.accounting_complete&&<option value="applied">Apply reconciled custody and disposal</option>}</select></label><Evidence name="evidence" label="Independent container review findings and evidence"/>{error&&<p role="alert">{error}</p>}<Button>Save container decision</Button></fieldset></form>:<p>Another pharmacist independent of these findings and preparation must review this proposal.</p>)}{success&&<p role="status">{success}</p>}</article>
}
