'use client'
import {FormEvent,useRef,useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {Button} from '@/components/ui/button'
import {Field,errorMessage} from './fields'
import {ContainerLabelSummary,useGetContainerLabelPrintsQuery,useCreateContainerLabelPrintMutation} from '@/store/api/pharmacyApiSlice'
export function ContainerLabelPrints({proof,disabled}:{proof:ContainerLabelSummary;disabled:boolean}){
 const [open,setOpen]=useState(false)
 return <div><Button variant="outline" onClick={()=>setOpen(!open)}>{open?'Close print evidence':`Print evidence for proof ${proof.id}`}</Button>{open&&<Records proof={proof} disabled={disabled}/>}</div>
}
function Records({proof,disabled}:{proof:ContainerLabelSummary;disabled:boolean}){
 const {user}=useAuth();const [page,setPage]=useState(1);const q=useGetContainerLabelPrintsQuery({id:proof.id,page});const [save,{isLoading}]=useCreateContainerLabelPrintMutation();const [error,setError]=useState('');const [success,setSuccess]=useState('');const [formKey,setFormKey]=useState(0);const request=useRef<{body:string;id:string}|null>(null)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setSuccess('');const f=new FormData(e.currentTarget);const body={id:proof.id,document_hash:proof.document_hash,copies:Number(f.get('copies')),occurred_on:String(f.get('occurred_on')),reason:String(f.get('reason')),reference:String(f.get('reference')),confirmed:f.get('confirmed')==='on'};const serialized=JSON.stringify(body);if(request.current?.body!==serialized)request.current={body:serialized,id:crypto.randomUUID()};try{await save({...body,request_id:request.current.id}).unwrap();request.current=null;setFormKey(k=>k+1);setPage(1);setSuccess('Simulated output evidence retained. No printer command was sent and no medication release was authorized.')}catch(err){setError(errorMessage(err))}}
 return <section className="space-y-3 pt-3"><h4 className="font-semibold">Print and reprint evidence · Proof {proof.id}</h4><p>Record simulated output for the exact retained document. Each reprint needs its own reason. These records do not prove that a physical printer produced a label.</p>
 {q.isError?<p role="alert">Print history unavailable. <Button onClick={()=>q.refetch()}>Retry container print history</Button></p>:!q.currentData?<p>Loading print history…</p>:<>{q.currentData.data.data.map(p=><article key={p.id} className="border rounded p-3 space-y-1"><p>Evidence {p.id} · {p.copies} copies · Reported {p.occurred_on} · Staff {p.created_by}</p><p>Reason: {p.reason}</p><p>Output check: {p.reference}</p><p>Recorded {p.created_at}</p><details><summary>Exact document hash</summary><code className="break-all">{p.document_hash}</code></details></article>)}{!q.currentData.data.total&&<p>No print evidence retained.</p>}<div className="flex flex-wrap gap-2 items-center"><Button disabled={page===1||q.isFetching} onClick={()=>setPage(page-1)}>Previous container prints</Button><span>Page {page} / {q.currentData.data.last_page}</span><Button disabled={page>=q.currentData.data.last_page||q.isFetching} onClick={()=>setPage(page+1)}>Next container prints</Button></div></>}
 {user?.role==='pharmacist'&&<form key={formKey} onSubmit={submit}><fieldset disabled={disabled||q.isFetching||q.isError||!q.currentData||isLoading} className="grid gap-3"><p>Open and inspect the retained proof before recording evidence. Superseded proofs or changed source evidence require a new proof.</p><Field name="copies" label="Simulated copy count" type="number" min={1} max={20} step={1} defaultValue={1}/><Field name="occurred_on" label="Simulated output date" type="date"/><Field name="reason" label="Container print or reprint reason" maxLength={2000}/><label className="grid gap-1">Container output-check evidence<textarea name="reference" required maxLength={5000} rows={3} className="border rounded p-2 bg-background"/></label><label className="flex items-start gap-2"><input name="confirmed" type="checkbox" required/>I compared the exact synthetic proof and recorded the simulated copies and output check. No physical printing or dispensing is certified.</label><Button>{isLoading?'Saving output evidence…':'Retain container print evidence'}</Button></fieldset></form>}{error&&<p role="alert">{error}</p>}{success&&<p role="status">{success}</p>}</section>
}
