"use client"
import Link from 'next/link'
import {FormEvent,useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Field,errorMessage} from './fields'
import {CompoundBatch,useGetIngredientLotsQuery,usePharmacyStockActionMutation} from '@/store/api/pharmacyApiSlice'
function LotChoice({location,name,label,onSelect}:{location:number;name:string;label:string;onSelect:(id:number)=>void}){
 const [search,setSearch]=useState(name.slice(0,100));const [page,setPage]=useState(1);const [value,setValue]=useState('');const {currentData,isFetching,isError}=useGetIngredientLotsQuery({page,search,location_id:location})
 return <div className="space-y-2"><Input aria-label={`Search stock for ${label}`} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);setValue('');onSelect(0)}}/>{isError?<p role="alert">Could not load ingredient stock.</p>:isFetching?<p>Loading stock…</p>:<label className="grid gap-1 text-sm">{label}<select required value={value} onChange={e=>{setValue(e.target.value);onSelect(Number(e.target.value))}} className="border rounded p-2 bg-background"><option value="">Select a reviewed ingredient receipt</option>{currentData?.data.data.filter(l=>l.status==='available').map(l=><option value={l.id} key={l.id}>{l.ingredient_name} · {l.supplier} · {l.lot_number} · {l.on_hand} {l.quantity_unit} on hand / {l.reserved} reserved · Expires {l.expires_on}</option>)}</select></label>}<div className="flex gap-3 items-center"><Button type="button" variant="outline" disabled={page===1||isFetching} onClick={()=>{setPage(page-1);setValue('');onSelect(0)}}>Previous lots</Button><span>{page} / {currentData?.data.last_page||1}</span><Button type="button" variant="outline" disabled={isFetching||page>=(currentData?.data.last_page||1)} onClick={()=>{setPage(page+1);setValue('');onSelect(0)}}>Next lots</Button></div></div>
}
export function IngredientAllocation({batch}:{batch:CompoundBatch}){
 const {user}=useAuth();const [save,{isLoading}]=usePharmacyStockActionMutation();const [selected,setSelected]=useState<Record<string,number>>({});const [error,setError]=useState('');const allocations=batch.allocations||[];const reserved=allocations.length>0&&allocations.every(a=>a.status==='reserved');const released=allocations.some(a=>a.status==='released')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const evidence=new FormData(e.currentTarget).get('evidence');try{await save({path:`batch-worksheets/${batch.id}/allocation`,body:{version:batch.version,action:reserved?'release':'reserve',evidence,...(!reserved?{lots:batch.record.ingredients.map(i=>({key:i.key,lot_id:selected[i.key]}))}:{})}}).unwrap()}catch(e){setError(errorMessage(e))}}
 return <section className="space-y-3 border-t pt-4"><h3 className="font-semibold">Ingredient stock reservation</h3><p className="text-sm">Reservations hold stock for this plan; on-hand quantities remain unchanged. A reservation does not clear a quarantined or expired lot for use. No manufacture or medication release is authorized.</p><Link className="underline" href="/dashboard/pharmacy/ingredients">Manage ingredient receipts and quarantine</Link>{allocations.map(a=><p key={a.id}>{batch.formula.record.ingredients.find(i=>i.key===a.ingredient_key)?.name}: {a.quantity} {a.quantity_unit} · Lot {a.lot_number} · Allocation {a.status} · Stock {a.lot_status} · Expires {a.lot_expires_on}</p>)}{released?<p>This reservation was released. Create a new worksheet to plan again.</p>:user?.role==='pharmacist'&&batch.status==='reviewed'?<form onSubmit={submit} className="space-y-4">{!reserved&&<><p className="text-sm">Select the exact receipt matching each worksheet source and formulation specification. Quarantined, expired, mismatched or insufficient stock will be rejected.</p>{batch.record.ingredients.map(i=><LotChoice key={i.key} location={batch.location_id} name={batch.formula.record.ingredients.find(f=>f.key===i.key)?.name||''} label={`${i.key} · ${i.quantity} ${i.unit} · ${i.supplier} · lot ${i.lot}`} onSelect={id=>setSelected(s=>({...s,[i.key]:id}))}/>)}</>}<Field name="evidence" label={reserved?'Reason for releasing reservation':'Stock reconciliation and selection evidence'}/>{error&&<p role="alert">{error}</p>}<Button disabled={isLoading||(!reserved&&batch.record.ingredients.some(i=>!selected[i.key]))}>{reserved?'Release all reserved ingredients':'Reserve exact ingredients'}</Button></form>:!allocations.length&&<p>Independent worksheet review is required before a pharmacist can reserve stock.</p>}</section>
}
