"use client"
import {FormEvent,useRef,useState} from 'react'
import {Button} from '@/components/ui/button'
import {useAuth} from '@/hooks/useAuth'
import {Field,errorMessage} from './fields'
import {CompoundBatch,PackagingContext,useGetPackagingHistoryQuery,useGetPackagingContextQuery,useGetPackagingProposalQuery,useCreatePackagingProposalMutation,useDecidePackagingProposalMutation} from '@/store/api/pharmacyApiSlice'
function Text({name,label}:{name:string;label:string}){return <label className="grid gap-1 text-sm">{label}<textarea name={name} required maxLength={5000} rows={3} className="border rounded p-2 bg-background"/></label>}
export function Packaging({batch}:{batch:CompoundBatch}){
 const {user}=useAuth();const id=batch.execution?.id??0;const [page,setPage]=useState(1);const [selected,setSelected]=useState<number|null>(null);const [creating,setCreating]=useState(false)
 const q=useGetPackagingHistoryQuery({id,page},{skip:!id});const latest=useGetPackagingHistoryQuery({id,page:1},{skip:!id})
 if(!id)return null
 if(q.isError||latest.isError)return <p role="alert">Could not load packaging proposals. <Button onClick={()=>{q.refetch();latest.refetch()}}>Retry packaging history</Button></p>
 if(!q.currentData||!latest.currentData)return <p>Loading packaging proposals…</p>
 const last=latest.currentData.data.data[0];const busy=q.isFetching||latest.isFetching
 return <section className="border-t pt-4 space-y-4"><h3 className="text-lg font-semibold">Finished packaging proposals</h3><p className="text-sm">Record identifiable containers against reviewed quality and dating evidence. All output remains quarantined; documentary review does not authorize dispensing.</p>{q.currentData.data.data.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-2 border-b pb-2"><p>Packaging proposal {p.id} · {p.status}</p><Button variant="outline" disabled={busy} onClick={()=>{setSelected(p.id);setCreating(false)}}>Open packaging proposal {p.id}</Button></div>)}{!q.currentData.data.total&&<p>No retained packaging proposals.</p>}<div className="flex gap-3 items-center"><Button variant="outline" disabled={busy||page===1} onClick={()=>setPage(page-1)}>Previous packaging proposals</Button><span>Page {page} / {q.currentData.data.last_page}</span><Button variant="outline" disabled={busy||page>=q.currentData.data.last_page} onClick={()=>setPage(page+1)}>Next packaging proposals</Button></div>
 {user?.role==='pharmacist'&&(last?.status==='pending'?<p>Review or reject the pending packaging proposal before retaining a replacement.</p>:<Button disabled={busy} variant="outline" onClick={()=>{setCreating(!creating);setSelected(null)}}>{creating?'Close packaging form':'Propose finished packaging'}</Button>)}
 {creating&&<fieldset disabled={busy} className="min-w-0"><Context execution={id} previous={last?.id??null} onDone={value=>{setCreating(false);setSelected(value);setPage(1)}}/></fieldset>}{selected&&<Detail key={selected} id={selected} batch={batch}/>}</section>
}
function Context({execution,previous,onDone}:{execution:number;previous:number|null;onDone:(id:number)=>void}){
 const q=useGetPackagingContextQuery(execution)
 if(q.isError)return <p role="alert">Packaging prerequisites are unavailable. {errorMessage(q.error)} <Button onClick={()=>q.refetch()}>Retry packaging prerequisites</Button></p>
 if(!q.currentData)return <p>Checking reviewed quality and dating evidence…</p>
 return <fieldset disabled={q.isFetching} className="min-w-0"><Create context={q.currentData.data} previous={previous} onDone={onDone}/></fieldset>
}
function Create({context,previous,onDone}:{context:PackagingContext;previous:number|null;onDone:(id:number)=>void}){
 const initial=useRef({context,previous}).current;const request=useRef<{payload:string;id:string}|null>(null);const [rows,setRows]=useState([1]);const next=useRef(2)
 const [save,{isLoading}]=useCreatePackagingProposalMutation();const [error,setError]=useState('');const source=initial.context
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const v=(key:string)=>String(f.get(key)??'')
 const body={id:source.execution_id,previous_id:initial.previous,source_hash:source.source_hash,proposal:{unit:source.output_balance.unit,unpackaged_quantity:v('unpackaged_quantity'),evidence:v('evidence'),containers:rows.map(id=>({identifier:v(`identifier_${id}`),quantity:v(`quantity_${id}`),container_reference:v(`container_${id}`),storage_reference:v(`storage_${id}`)}))}}
 const payload=JSON.stringify(body);if(request.current?.payload!==payload)request.current={payload,id:crypto.randomUUID()}
 try{const r=await save({...body,request_id:request.current.id}).unwrap();onDone(r.data.id)}catch(e){setError(errorMessage(e))}}
 const changed=context.source_hash!==source.source_hash
 return <form onSubmit={submit} className="rounded border p-4 space-y-3"><h4 className="font-semibold">New packaging proposal</h4><p>Reviewed dating proposal: {source.dating_proposal_id}. Held output: {source.output_balance.held_output} {source.output_balance.unit}.</p><p className="text-sm">Container quantities plus unpackaged output must equal held output. Enter exact quantities with up to three decimal places. Identifiers use uppercase letters, numbers, hyphens or underscores and remain reserved to this preparation even after rejection.</p>{changed&&<p role="alert">Source evidence changed. Preserve your notes, then close and reopen this form.</p>}<fieldset disabled={isLoading||changed} className="min-w-0 space-y-3">{rows.map((id,i)=><fieldset key={id} className="border rounded p-3 space-y-2"><legend>Container {i+1}</legend><Field name={`identifier_${id}`} label={`Container ${i+1} identifier`} maxLength={64}/><Field name={`quantity_${id}`} label={`Container ${i+1} quantity (${source.output_balance.unit})`}/><Text name={`container_${id}`} label={`Container ${i+1} packaging evidence`}/><Text name={`storage_${id}`} label={`Container ${i+1} storage evidence`}/>{rows.length>1&&<Button type="button" variant="outline" onClick={()=>setRows(rows.filter(r=>r!==id))}>Remove container {i+1}</Button>}</fieldset>)}<Button type="button" variant="outline" disabled={rows.length>=100} onClick={()=>setRows([...rows,next.current++])}>Add container</Button><Field name="unpackaged_quantity" label={`Unpackaged quantity (${source.output_balance.unit}), including explicit zero`}/><Text name="evidence" label="Packaging observations and evidence"/>{error&&<p role="alert">{error}</p>}<Button>Retain packaging proposal</Button></fieldset></form>
}
function Detail({id,batch}:{id:number;batch:CompoundBatch}){
 const {user}=useAuth();const q=useGetPackagingProposalQuery(id);const [save,{isLoading}]=useDecidePackagingProposalMutation();const [error,setError]=useState('');const [success,setSuccess]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setSuccess('');const f=new FormData(e.currentTarget);try{await save({id,decision:String(f.get('decision')) as 'reviewed'|'rejected',evidence:String(f.get('evidence'))}).unwrap();setSuccess('Packaging decision retained. Output remains quarantined.')}catch(e){setError(errorMessage(e))}}
 if(q.isError)return <p role="alert">Could not load packaging evidence. <Button onClick={()=>q.refetch()}>Retry packaging detail</Button></p>
 if(!q.currentData)return <p>Loading packaging evidence…</p>
 const p=q.currentData.data;const v=p.proposal;const independent=Number(user?.id)!==p.created_by&&Number(user?.id)!==batch.execution?.created_by&&!batch.execution?.addenda.some(a=>a.created_by===Number(user?.id))
 return <article className="border rounded p-4 space-y-3"><h4 className="font-semibold">Packaging proposal {p.id} · {p.status}</h4><p>Dating proposal {p.dating_proposal_id} · Recorded by user {p.created_by} · {p.created_at}</p><p>Packaged: {v.packaged_quantity} {v.unit} · Unpackaged: {v.unpackaged_quantity} {v.unit} · Held: {v.held_output} {v.unit}</p><p>Previously disposed: {v.previously_disposed} {v.unit}. No new stock is created.</p>{v.containers.map(c=><div key={c.identifier} className="border-b pb-2"><strong>{c.identifier} · {c.quantity} {v.unit} · quarantined</strong><p className="whitespace-pre-wrap break-words">Packaging: {c.container_reference}</p><p className="whitespace-pre-wrap break-words">Storage: {c.storage_reference}</p></div>)}<p className="whitespace-pre-wrap break-words">{v.evidence}</p>{p.reviewed_by&&<><p>Reviewed by user {p.reviewed_by} · {p.reviewed_at}</p><p className="whitespace-pre-wrap break-words">{p.review_evidence}</p></>}
 {p.status==='pending'&&user?.role==='pharmacist'&&(independent?<form onSubmit={submit}><fieldset disabled={isLoading||q.isFetching} className="space-y-3"><label className="grid gap-1 text-sm">Packaging proposal decision<select name="decision" defaultValue="rejected" className="border rounded p-2 bg-background"><option value="rejected">Reject proposal for replacement</option><option value="reviewed">Record independent documentary review</option></select></label><Text name="evidence" label="Packaging review findings and evidence"/>{error&&<p role="alert">{error}</p>}<Button>Save packaging decision</Button></fieldset></form>:<p>Another pharmacist independent of packaging and preparation must review this proposal.</p>)}{success&&<p role="status">{success}</p>}</article>
}
