"use client"
import {useState} from 'react'
import {PharmacyLotDetail,usePharmacyStockActionMutation} from '@/store/api/pharmacyApiSlice'
import {Field,Choice,errorMessage} from './fields'
import {Button} from '@/components/ui/button'
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card'
export function StockCountReconciliation({lot,userId,role,page,changePage,refreshing}:{lot:PharmacyLotDetail;userId:number;role:string;page:number;changePage:(n:number)=>void;refreshing:boolean}){
 const recalled=!!lot.recall_reference||lot.recall_notices.length>0
 const [key,setKey]=useState(()=>crypto.randomUUID());const [error,setError]=useState('');const [success,setSuccess]=useState('');const [mutate,{isLoading}]=usePharmacyStockActionMutation()
 async function save(path:string,body:Record<string,unknown>){setError('');setSuccess('');try{await mutate({path:`stock/${lot.id}/${path}`,body}).unwrap();if(path==='counts')setKey(crypto.randomUUID());setSuccess('Saved. The count and stock history have been updated.')}catch(e){setError(errorMessage(e))}}
 return <Card><CardHeader><CardTitle>Physical-count reconciliation</CardTitle></CardHeader><CardContent className="space-y-4"><p>Record a discrepancy between physically present stock and the recorded balance. The receipt is quarantined immediately; quantities change only after a different pharmacist reviews and applies the count. Damaged stock still physically present belongs in the count. This does not record disposal, a return or controlled-substance loss reporting.</p>{error&&<p role="alert" className="text-destructive">{error}</p>}{success&&<p role="status">{success}</p>}{recalled?<p>Recalled receipts require separate disposition handling; a count cannot clear the recall or change its balance.</p>:lot.count_pending?<p role="status">A discrepancy is awaiting independent pharmacist review. Stock remains quarantined.</p>:<details><summary className="underline cursor-pointer">Record physical-count discrepancy</summary><form className="grid gap-3 mt-3" onSubmit={e=>{e.preventDefault();save('counts',{...Object.fromEntries(new FormData(e.currentTarget)),version:lot.version,request_id:key})}}><p>Current recorded balance: {lot.on_hand} {lot.quantity_unit}. Record the actual observed quantity, including when it is below reservations. Review cannot apply a balance below reserved stock.</p><Field name="counted_quantity" label={`Physical quantity counted (${lot.quantity_unit})`} type="number" min="0" max="999999.999" step="0.001"/><Choice name="reason" label="Count reason" options={['physical_count','observed_loss']}/><label className="grid gap-1 text-sm">Count evidence and discrepancy explanation<textarea name="evidence" className="border rounded p-2 bg-background" required maxLength={5000}/></label><Button disabled={isLoading||refreshing}>Record discrepancy and quarantine</Button></form></details>}
 {lot.counts.data.map(c=><div key={c.id} className="border rounded p-3 space-y-2 break-words"><h3 className="font-semibold">Count #{c.id} · {c.status}</h3><p>Recorded {c.recorded_quantity} · Counted {c.counted_quantity} {lot.quantity_unit} · {c.reason.replaceAll('_',' ')}</p><p>By staff #{c.created_by} · {c.created_at}</p><p className="whitespace-pre-wrap">{c.evidence}</p>{c.reviewed_at&&<div><p>Reviewed by pharmacist #{c.reviewed_by} · {c.reviewed_at}</p><p className="whitespace-pre-wrap">{c.review_evidence}</p></div>}{c.status==='pending'&&(role==='pharmacist'&&Number(c.created_by)!==userId?<form className="grid gap-3" onSubmit={e=>{e.preventDefault();save(`counts/${c.id}/review`,Object.fromEntries(new FormData(e.currentTarget)))}}><Choice name="decision" label={`Decision for count ${c.id}`} options={recalled?['reject']:['reject','apply']}/><label className="grid gap-1 text-sm">Independent review evidence for count {c.id}<textarea name="evidence" className="border rounded p-2 bg-background" required maxLength={5000}/></label><p>Applying requires unchanged stock since the count and enough units to cover reservations. Quarantine remains after applying or rejecting; release needs a separate stock review.</p><Button disabled={isLoading||refreshing}>Record review for count {c.id}</Button></form>:<p>A different assigned pharmacist must review this discrepancy.</p>)}</div>)}{!lot.counts.data.length&&<p>No count discrepancies recorded.</p>}
 <div className="flex flex-wrap items-center gap-3"><Button variant="outline" disabled={page===1||isLoading||refreshing} onClick={()=>changePage(page-1)}>Previous counts</Button><span>Page {page} of {lot.counts.last_page} · {lot.counts.total} counts</span><Button variant="outline" disabled={page>=lot.counts.last_page||isLoading||refreshing} onClick={()=>changePage(page+1)}>Next counts</Button></div>
 </CardContent></Card>
}
