"use client"
import Link from 'next/link'
import {useState} from 'react'
import {PharmacyLotDetail,useGetStockTransferDestinationsQuery,usePharmacyStockActionMutation} from '@/store/api/pharmacyApiSlice'
import {Field,errorMessage} from './fields'
import {Button} from '@/components/ui/button'
export function StockTransferPlan({lot,refreshing}:{lot:PharmacyLotDetail;refreshing:boolean}){
 const {data,isError,isFetching}=useGetStockTransferDestinationsQuery();const [mutate,{isLoading}]=usePharmacyStockActionMutation();const [key,setKey]=useState(()=>crypto.randomUUID());const [error,setError]=useState('');const [created,setCreated]=useState<number|null>(null)
 async function save(form:HTMLFormElement){setError('');setCreated(null);const body=Object.fromEntries(new FormData(form));try{const result=await mutate({path:'stock-transfers',body:{...body,source_lot_id:lot.id,destination_location_id:Number(body.destination_location_id),version:lot.version,request_id:key}}).unwrap();setCreated(result.data.id);setKey(crypto.randomUUID())}catch(e){setError(errorMessage(e))}}
 return <details className="border rounded p-4"><summary className="underline cursor-pointer">Plan transfer to another location</summary><div className="space-y-3 mt-3"><p className="text-sm">Synthetic custody record. Planning reserves stock here. Dispatch removes it from this location; a different pharmacist must record receipt at the destination. Every receipt begins in quarantine.</p>{error&&<p role="alert" className="text-destructive">{error}</p>}{created&&<p role="status">Transfer planned. <Link className="underline" href={`/dashboard/pharmacy/transfers/${created}`}>Open transfer #{created}</Link></p>}{isError?<p role="alert">Receiving locations could not be loaded.</p>:lot.status!=='available'||lot.count_pending||lot.recall_reference?<p>Resolve this receipt&apos;s hold before planning a transfer.</p>:<form key={key} className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save(e.currentTarget)}}><label className="grid gap-1 text-sm">Destination location<select name="destination_location_id" required className="border rounded p-2 bg-background" defaultValue=""><option value="">Select receiving location</option>{data?.data.filter(l=>l.id!==lot.location_id).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><Field name="quantity" label={`Quantity to transfer (${lot.quantity_unit})`} type="number" min="0.001" max={Math.max(0,Number(lot.on_hand)-Number(lot.reserved))} step="0.001"/><Field name="reference" label="Transfer purpose and supporting reference" maxLength={2000}/><Button disabled={isLoading||refreshing||isFetching}>Reserve transfer stock</Button></form>}</div></details>
}
