"use client"
import Link from 'next/link'
import {StockTransfer} from '@/store/api/pharmacyApiSlice'
import {Field,Choice} from './fields'
import {Button} from '@/components/ui/button'
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card'
export function TransferCorrections({transfer:t,userId,role,disabled,page,changePage,save}:{transfer:StockTransfer;userId:number;role:string;disabled:boolean;page:number;changePage:(p:number)=>void;save:(path:string,body:Record<string,unknown>)=>void}){
 return <Card><CardHeader><CardTitle>Receipt-entry correction</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm">Use this only when the arrival quantity was entered incorrectly. Record and independently review a physical count at the destination first. It must match the original dispatch. A different pharmacist at the sending location then reviews the evidence. The original receipt is retained, and stock remains quarantined for a separate release review. Actual loss, additional deliveries and unexplained excess require investigation.</p>
 {t.status==='received_discrepancy'&&t.can_receive&&role==='pharmacist'&&!t.correction_pending&&<><Link className="underline" href={`/dashboard/pharmacy/stock/${t.destination_lot_id}`}>Open destination receipt to record or review its physical count</Link>{t.correction_candidates.length?<form className="grid gap-3" onSubmit={e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));save('corrections',{...body,stock_count_id:Number(body.stock_count_id)})}}><label className="grid gap-1 text-sm">Reviewed physical count<select className="border rounded p-2 bg-background" name="stock_count_id" required defaultValue=""><option value="">Select reviewed count</option>{t.correction_candidates.map(c=><option key={c.id} value={c.id}>Count #{c.id} · {c.counted_quantity} {t.product.quantity_unit} · Reviewer #{c.reviewed_by}</option>)}</select></label><Field name="evidence" label="Receipt-entry error and supporting evidence" maxLength={5000}/><label className="flex items-start gap-2 text-sm"><input type="checkbox" required/>This corrects the original entry; it does not represent new stock, a loss write-off or an unverified quantity.</label><Button disabled={disabled}>Propose receipt correction</Button></form>:<p>No independently applied physical count is available yet.</p>}</>}
 {t.correction_pending&&<p>A proposal awaits independent review at the sending location. Stock remains on custody hold.</p>}
 {t.corrections.data.map(c=><div className="border rounded p-4 space-y-2 break-words" key={c.id}><h3 className="font-semibold">Correction #{c.id} · {c.status}</h3><p>Proposed by pharmacist #{c.created_by} · {c.created_at}</p><p>{c.evidence}</p><p>Physical count #{c.stock_count_id}: {c.verified_quantity} {t.product.quantity_unit} · Independently reviewed by #{c.count_reviewed_by}</p><details><summary className="underline cursor-pointer">Physical-count evidence</summary><p className="whitespace-pre-wrap mt-2">{c.count_evidence}</p><p className="whitespace-pre-wrap">Review: {c.count_review_evidence}</p></details>{c.reviewed_by&&<p>Decision by pharmacist #{c.reviewed_by} · {c.reviewed_at}<br/>{c.review_evidence}</p>}
 {c.status==='pending'&&role==='pharmacist'&&t.can_dispatch&&(c.created_by===userId?<p>A different sending-location pharmacist must review your proposal.</p>:<form className="grid gap-3 pt-3" onSubmit={e=>{e.preventDefault();save(`corrections/${c.id}/review`,Object.fromEntries(new FormData(e.currentTarget)))}}><Choice name="decision" label={`Decision for correction #${c.id}`} options={['reject','apply']}/><Field name="evidence" label={`Review evidence for correction #${c.id}`} maxLength={5000}/><label className="flex items-start gap-2 text-sm"><input type="checkbox" required/>I reviewed the original dispatch, arrival entry and independently verified physical count.</label><Button disabled={disabled}>Record correction decision</Button></form>)}</div>)}
 {!t.corrections.data.length&&<p>No receipt corrections recorded.</p>}<div className="flex flex-wrap gap-3 items-center"><Button variant="outline" disabled={disabled||page===1} onClick={()=>changePage(page-1)}>Previous corrections</Button><span>Page {page} of {t.corrections.last_page}</span><Button variant="outline" disabled={disabled||page>=t.corrections.last_page} onClick={()=>changePage(page+1)}>Next corrections</Button></div></CardContent></Card>
}
