"use client"
import Link from 'next/link'
import {useParams} from 'next/navigation'
import {useState} from 'react'
import {useAuth} from '@/hooks/useAuth'
import {useGetPharmacyStockLotQuery,usePharmacyStockActionMutation} from '@/store/api/pharmacyApiSlice'
import {StockTransferPlan} from '@/components/pharmacy/StockTransferPlan'
import {StockCountReconciliation} from '@/components/pharmacy/StockCountReconciliation'
import {Field,errorMessage} from '@/components/pharmacy/fields'
import {Button} from '@/components/ui/button'
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card'
export default function StockReceipt(){
 const id=Number(useParams().id);const {user}=useAuth();const role=user?.role||'';const allowed=['pharmacist','pharmacy_technician'].includes(role)
 const [countPage,setCountPage]=useState(1);const [fillPage,setFillPage]=useState(1);const [eventPage,setEventPage]=useState(1);const [requestId]=useState(()=>crypto.randomUUID());const [error,setError]=useState('');const [success,setSuccess]=useState('')
 const {currentData,isFetching,isError,refetch}=useGetPharmacyStockLotQuery({id,fill_page:fillPage,event_page:eventPage,count_page:countPage},{skip:!allowed||!Number.isInteger(id)||id<1});const [mutate,{isLoading}]=usePharmacyStockActionMutation();const lot=currentData?.data
 async function recall(body:Record<string,unknown>){setError('');setSuccess('');try{await mutate({path:`stock/${id}/recall`,body:{...body,version:lot?.version,request_id:requestId}}).unwrap();setSuccess('Recall hold recorded. Review the linked fills and resolve outstanding reservations.')}catch(e){setError(errorMessage(e))}}
 if(!allowed)return <p>Pharmacy staff access is required.</p>
 return <div className="space-y-6 min-w-0"><Link className="underline" href="/dashboard/pharmacy/stock">Back to inventory</Link><h1 className="text-3xl font-bold text-primary">Stock receipt #{id}</h1><p className="text-sm">Synthetic preview. This trace concerns one receipt only. A receipt hold does not identify every matching lot across locations, notify patients, or record physical recovery, disposal or recall closure.</p>{error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}{success&&<p role="status">{success}</p>}{isError?<p role="alert">Could not load this receipt. <Button variant="outline" onClick={()=>refetch()}>Retry</Button></p>:isFetching&&!lot?<p role="status">Loading receipt…</p>:lot&&<>
 <Card><CardHeader><CardTitle>{lot.medication}</CardTitle></CardHeader><CardContent className="space-y-2 break-words"><p>NDC {lot.ndc} · Lot {lot.lot_number} · Location #{lot.location_id}</p><p>Expires {lot.expires_on} · Status: {lot.status}</p><p>On hand {lot.on_hand} · Reserved {lot.reserved} {lot.quantity_unit}</p><p>Receipt evidence: {lot.receipt_reference}</p>{lot.custody_hold&&<p role="alert" className="font-semibold text-red-700 dark:text-red-300">Custody hold: {lot.custody_hold}</p>}{lot.source_transfer_id&&<Link className="underline" href={`/dashboard/pharmacy/transfers/${lot.source_transfer_id}`}>View source transfer #{lot.source_transfer_id}</Link>}</CardContent></Card>
 {lot.recall_reference?<Card><CardHeader><CardTitle>Recall hold recorded</CardTitle></CardHeader><CardContent className="space-y-2 break-words"><p>{lot.recall_reference}</p><p className="whitespace-pre-wrap">{lot.recall_evidence}</p><p>Recorded {lot.recalled_at} · Pharmacist #{lot.recalled_by}</p><p>New reservations, preparation and handover are blocked. Cancel open fills explicitly to release reservations. Completed fills remain in the trace. Ordinary stock release cannot clear this hold.</p></CardContent></Card>:role==='pharmacist'&&<details className="border rounded p-4"><summary className="underline cursor-pointer">Record receipt recall hold</summary><form className="grid gap-3 mt-3" onSubmit={e=>{e.preventDefault();recall(Object.fromEntries(new FormData(e.currentTarget)))}}><p>This retained hold blocks use of this receipt without changing its recorded quantities. Review the notice and receipt identity before recording. There is no recall-clear action.</p><Field name="reference" label="Recall notice / source reference" maxLength={2000}/><label className="grid gap-1 text-sm">Recall evidence and receipt match<textarea name="evidence" className="border rounded p-2 bg-background" required maxLength={5000}/></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" required/>I have checked the notice against this receipt and will follow up on the linked fills.</label><Button variant="destructive" disabled={isLoading||isFetching}>Record recall hold</Button></form></details>}
 {lot.recall_notices.length>0&&<section className="border border-destructive rounded p-4 space-y-2"><h2 className="font-semibold">Matching organization recall notices</h2>{lot.recall_notices.map(n=><Link key={n.id} className="block underline break-words" href={`/dashboard/pharmacy/recalls/${n.id}`}>{n.reference} · {n.product_description}</Link>)}<Link className="block underline" href="/dashboard/pharmacy/recalls">View the complete recall register</Link></section>}
 {role==='pharmacist'&&<StockTransferPlan key={`${user?.id}-${id}`} lot={lot} refreshing={isFetching}/>}
 <StockCountReconciliation key={`${user?.id}-${id}`} lot={lot} userId={Number(user?.id)} role={role} page={countPage} changePage={setCountPage} refreshing={isFetching}/>
 <Card><CardHeader><CardTitle>Fill trace</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm">Pending and ready fills retain stock reservations. Collected and delivered fills record prior handover; review the prescription for recipient and follow-up evidence. Cancelled fills are retained history.</p>{lot.trace.data.map(f=><div key={f.id} className="border rounded p-3 space-y-1 break-words"><Link className="underline" href={`/dashboard/pharmacy/${f.prescription_id}#fill-${f.id}`}>{f.rx_number} · Fill {f.fill_number}</Link><p>{f.quantity} {lot.quantity_unit} · {f.fulfillment_status} · Created {f.created_at}</p></div>)}{!lot.trace.data.length&&<p>No fills recorded against this receipt.</p>}<Pager page={fillPage} pages={lot.trace.last_page} total={lot.trace.total} label="fills" change={setFillPage}/></CardContent></Card>
 <Card><CardHeader><CardTitle>Stock history</CardTitle></CardHeader><CardContent className="space-y-3">{lot.events.data.map(e=><div key={e.id} className="border rounded p-3 break-words"><p>{e.action.replaceAll('_',' ')} · {e.quantity} {lot.quantity_unit} · Staff #{e.actor_id}</p><p>{e.created_at}{e.fill_id?` · Fill record #${e.fill_id}`:''}</p><details><summary className="underline cursor-pointer">Recorded evidence</summary><pre className="whitespace-pre-wrap break-words text-xs mt-2">{e.details}</pre></details></div>)}{!lot.events.data.length&&<p>No stock events recorded.</p>}<Pager page={eventPage} pages={lot.events.last_page} total={lot.events.total} label="events" change={setEventPage}/></CardContent></Card>
 </>}</div>
}
function Pager({page,pages,total,label,change}:{page:number;pages:number;total:number;label:string;change:(p:number)=>void}){return <div className="flex flex-wrap items-center gap-3"><Button variant="outline" disabled={page===1} onClick={()=>change(page-1)}>Previous {label}</Button><span>Page {page} of {pages} · {total} {label}</span><Button variant="outline" disabled={page>=pages} onClick={()=>change(page+1)}>Next {label}</Button></div>}
